# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_copy_copy1.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import Home
import calculadora2
import sys
sys.path.append('../DB_SQL')
import dbSQLClass

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, sectionVector, socket):
        self.s = socket
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.MainWindow = MainWindow
        self.sectionVector = sectionVector
        self.instanciaBD_alarmas = dbSQLClass.DataBaseQueries()
        self.alarmasAlmacenadas = self.instanciaBD_alarmas.get_PID_Data()

        self.MainWindow = MainWindow
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 82, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 123, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 102, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 82, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 82, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 123, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 102, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 82, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 82, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 123, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 102, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 82, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 82, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 82, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(290, 110, 191, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(660, 0, 131, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../images/quirema.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.titleAlarm = QtWidgets.QLabel(self.centralWidget)
        self.titleAlarm.setGeometry(QtCore.QRect(270, 100, 291, 41))
        self.titleAlarm.setStyleSheet("color: white; font-size: 22pt")
        self.titleAlarm.setObjectName("titleAlarm")
        self.on_offLabel = QtWidgets.QLabel(self.centralWidget)
        self.on_offLabel.setGeometry(QtCore.QRect(330, 140, 110, 31))
        self.on_offLabel.setStyleSheet("color: white; font-size: 22pt")
        self.on_offLabel.setObjectName("on_offLabel")
        self.valueLabel = QtWidgets.QLabel(self.centralWidget)
        self.valueLabel.setGeometry(QtCore.QRect(500, 140, 81, 31))
        self.valueLabel.setStyleSheet("color: white; font-size: 22pt")
        self.valueLabel.setObjectName("valueLabel")
        self.mantasLabel = QtWidgets.QLabel(self.centralWidget)
        self.mantasLabel.setGeometry(QtCore.QRect(90, 190, 231, 31))
        self.mantasLabel.setStyleSheet("color: white; font-size: 19pt")
        self.mantasLabel.setObjectName("mantasLabel")
        self.tempHorno1Label = QtWidgets.QLabel(self.centralWidget)
        self.tempHorno1Label.setGeometry(QtCore.QRect(90, 230, 231, 31))
        self.tempHorno1Label.setStyleSheet("color: white; font-size: 19pt")
        self.tempHorno1Label.setObjectName("tempHorno1Label")
        self.tempHorno2Label = QtWidgets.QLabel(self.centralWidget)
        self.tempHorno2Label.setGeometry(QtCore.QRect(90, 270, 231, 31))
        self.tempHorno2Label.setStyleSheet("color: white; font-size: 19pt")
        self.tempHorno2Label.setObjectName("tempHorno2Label")
        self.tempHorno3Label = QtWidgets.QLabel(self.centralWidget)
        self.tempHorno3Label.setGeometry(QtCore.QRect(90, 310, 231, 31))
        self.tempHorno3Label.setStyleSheet("color: white; font-size: 19pt")
        self.tempHorno3Label.setObjectName("tempHorno3Label")
        self.tempHorno4Label = QtWidgets.QLabel(self.centralWidget)
        self.tempHorno4Label.setGeometry(QtCore.QRect(90, 350, 231, 31))
        self.tempHorno4Label.setStyleSheet("color: white; font-size: 19pt")
        self.tempHorno4Label.setObjectName("tempHorno4Label")
        self.radioButtonManta = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButtonManta.setGeometry(QtCore.QRect(360, 190, 20, 21))
        self.radioButtonManta.setText("")
        self.radioButtonManta.setObjectName("radioButtonManta")
        self.radioButtonHorno1 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButtonHorno1.setGeometry(QtCore.QRect(360, 230, 20, 21))
        self.radioButtonHorno1.setText("")
        self.radioButtonHorno1.setObjectName("radioButtonHorno1")
        self.radioButtonHorno2 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButtonHorno2.setGeometry(QtCore.QRect(360, 270, 20, 21))
        self.radioButtonHorno2.setText("")
        self.radioButtonHorno2.setObjectName("radioButtonHorno2")
        self.radioButtonHorno3 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButtonHorno3.setGeometry(QtCore.QRect(360, 320, 20, 21))
        self.radioButtonHorno3.setText("")
        self.radioButtonHorno3.setObjectName("radioButtonHorno3")
        self.radioButtonHorno4 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButtonHorno4.setGeometry(QtCore.QRect(360, 360, 20, 21))
        self.radioButtonHorno4.setText("")
        self.radioButtonHorno4.setObjectName("radioButtonHorno4")
        self.pushButtonManta = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonManta.setGeometry(QtCore.QRect(480, 180, 95, 31))
        self.pushButtonManta.setObjectName("pushButtonManta")
        self.pushButtonHorno1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonHorno1.setGeometry(QtCore.QRect(480, 220,  95, 31))
        self.pushButtonHorno1.setObjectName("pushButtonHorno1")
        self.pushButtonHorno2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonHorno2.setGeometry(QtCore.QRect(480, 260,  95, 31))
        self.pushButtonHorno2.setObjectName("pushButtonHorno2")
        self.pushButtonHorno3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonHorno3.setGeometry(QtCore.QRect(480, 300,  95, 31))
        self.pushButtonHorno3.setObjectName("pushButtonHorno3")
        self.pushButtonHorno4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonHorno4.setGeometry(QtCore.QRect(480, 340,  95, 31))
        self.pushButtonHorno4.setObjectName("pushButtonHorno4")
        self.labelCelsiusMantas = QtWidgets.QLabel(self.centralWidget)
        self.labelCelsiusMantas.setGeometry(QtCore.QRect(580, 180, 71, 31))
        self.labelCelsiusMantas.setStyleSheet("font-size: 16pt;color:white")
        self.labelCelsiusMantas.setObjectName("labelCelsiusMantas")
        self.labelCelsiusHorno1 = QtWidgets.QLabel(self.centralWidget)
        self.labelCelsiusHorno1.setGeometry(QtCore.QRect(580, 220, 71, 31))
        self.labelCelsiusHorno1.setStyleSheet("font-size: 16pt;color:white")
        self.labelCelsiusHorno1.setObjectName("labelCelsiusHorno1")
        self.labelCelsiusHorno2 = QtWidgets.QLabel(self.centralWidget)
        self.labelCelsiusHorno2.setGeometry(QtCore.QRect(580, 260, 71, 31))
        self.labelCelsiusHorno2.setStyleSheet("font-size: 16pt;color:white")
        self.labelCelsiusHorno2.setObjectName("labelCelsiusHorno2")
        self.labelCelsiusHorno3 = QtWidgets.QLabel(self.centralWidget)
        self.labelCelsiusHorno3.setGeometry(QtCore.QRect(580, 300, 71, 31))
        self.labelCelsiusHorno3.setStyleSheet("font-size: 16pt;color:white")
        self.labelCelsiusHorno3.setObjectName("labelCelsiusHorno3")
        self.label_16 = QtWidgets.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(580, 340, 71, 31))
        self.label_16.setStyleSheet("font-size: 16pt;color:white")
        self.label_16.setObjectName("label_16")

        self.pushButtonHome = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonHome.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.pushButtonHome.setStyleSheet("background-color: #222222; color:white; font-size: 20pt;")
        self.pushButtonHome.setIcon(QtGui.QIcon('../images/home.png'))
        self.pushButtonHome.setIconSize(QtCore.QSize(31,31))

        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.actionButtons()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quirema"))
        self.label.setText(_translate("MainWindow", "                   Quirema                            Alarmas"))
        self.titleAlarm.setText(_translate("MainWindow", "Configuración alarmas"))
        self.on_offLabel.setText(_translate("MainWindow", "ON/OFF"))
        self.valueLabel.setText(_translate("MainWindow", "Valor"))
        self.mantasLabel.setText(_translate("MainWindow", "Temperatura mantas:"))
        self.tempHorno1Label.setText(_translate("MainWindow", "Temperatura horno 1:"))
        self.tempHorno2Label.setText(_translate("MainWindow", "Temperatura horno 2:"))
        self.tempHorno3Label.setText(_translate("MainWindow", "Temperatura horno 3:"))
        self.tempHorno4Label.setText(_translate("MainWindow", "Temperatura horno 4:"))
        self.pushButtonManta.setText(_translate("MainWindow", self.alarmasAlmacenadas[1]))
        self.pushButtonHorno1.setText(_translate("MainWindow", self.alarmasAlmacenadas[2]))
        self.pushButtonHorno2.setText(_translate("MainWindow", self.alarmasAlmacenadas[3]))
        self.pushButtonHorno3.setText(_translate("MainWindow", self.alarmasAlmacenadas[4]))
        self.pushButtonHorno4.setText(_translate("MainWindow", self.alarmasAlmacenadas[5]))
        self.labelCelsiusMantas.setText(_translate("MainWindow", "Celsius"))
        self.labelCelsiusHorno1.setText(_translate("MainWindow", "Celsius"))
        self.labelCelsiusHorno2.setText(_translate("MainWindow", "Celsius"))
        self.labelCelsiusHorno3.setText(_translate("MainWindow", "Celsius"))
        self.label_16.setText(_translate("MainWindow", "Celsius"))
        
    def actionButtons(self):
        self.pushButtonHome.clicked.connect(self.home)
        self.pushButtonManta.clicked.connect(lambda: self.setValuesCalculadora("buttonMantas"))
        self.pushButtonHorno1.clicked.connect(lambda: self.setValuesCalculadora("buttonHorno1"))
        self.pushButtonHorno2.clicked.connect(lambda: self.setValuesCalculadora("buttonHorno2"))
        self.pushButtonHorno3.clicked.connect(lambda: self.setValuesCalculadora("buttonHorno3"))
        self.pushButtonHorno4.clicked.connect(lambda: self.setValuesCalculadora("buttonHorno4"))

    def setValuesCalculadora(self, selectedButton):
        if selectedButton == "buttonMantas":
            button = self.pushButtonManta
            alarmaSeleccionada = "tempMantas"
        elif selectedButton == "buttonHorno1":
            button = self.pushButtonHorno1
            alarmaSeleccionada = "tempHorno1"
        elif selectedButton == "buttonHorno2":
            button = self.pushButtonHorno2
            alarmaSeleccionada = "tempHorno2"
        elif selectedButton == "buttonHorno3":
            button = self.pushButtonHorno3
            alarmaSeleccionada = "tempHorno3"
        elif selectedButton == "buttonHorno4":
            button = self.pushButtonHorno4
            alarmaSeleccionada = "tempHorno4"

        self.MainWindow.setEnabled(False)
        MainWindow = QtWidgets.QMainWindow()
        self.calculadora = calculadora2.Ui_MainWindow()
        self.calculadora.setupUi_Alarmas(MainWindow, alarmaSeleccionada, button, self.sectionVector, self.MainWindow)
        MainWindow.show()


    def home(self):
        self.home = Home.Ui_MainWindow()
        self.home.setupUi(self.MainWindow)
