# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/EstebanGarcia/Developer/reactorQuirema/interfaz/interfazQT/mainwindow_copy_copy2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import Home
import recetas1
import calculadora2
import serialClass
import threading
import time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, sectionVector, socket, sockeBomba):
        global variableAModificar, setValueFromCalculadora

        self.MainWindow = MainWindow
        self.s = socket
        self.sBomba = sockeBomba
        time.sleep(0.5)
        self.instanciaModbus = serialClass.modbus(self.s)
        self.flag_DesactivaVista = False
        variableAModificar = "0"
        setValueFromCalculadora = False

        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 480)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 123, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 102, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 123, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 102, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 123, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 102, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 82, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setIconSize(QtCore.QSize(70, 70))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 71))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(670, 0, 131, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../images/quirema.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton_Receta1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Receta1.setGeometry(QtCore.QRect(80, 90, 68, 25))
        self.pushButton_Receta1.setStyleSheet("")
        self.pushButton_Receta1.setObjectName("pushButton_Receta1")
        self.pushButton_Receta2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Receta2.setGeometry(QtCore.QRect(150, 90, 68, 25))
        self.pushButton_Receta2.setStyleSheet("")
        self.pushButton_Receta2.setObjectName("pushButton_Receta2")
        self.pushButton_Receta3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Receta3.setGeometry(QtCore.QRect(220, 90, 68, 25))
        self.pushButton_Receta3.setStyleSheet("")
        self.pushButton_Receta3.setObjectName("pushButton_Receta3")
        self.pushButton_Receta4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Receta4.setGeometry(QtCore.QRect(290, 90, 68, 25))
        self.pushButton_Receta4.setStyleSheet("")
        self.pushButton_Receta4.setObjectName("pushButton_Receta4")
        self.label_Horno1 = QtWidgets.QLabel(self.centralWidget)
        self.label_Horno1.setGeometry(QtCore.QRect(10, 130, 51, 16))
        self.label_Horno1.setStyleSheet("color: white")
        self.label_Horno1.setObjectName("label_Horno1")
        self.label_Horno2 = QtWidgets.QLabel(self.centralWidget)
        self.label_Horno2.setGeometry(QtCore.QRect(10, 160, 51, 16))
        self.label_Horno2.setStyleSheet("color: white")
        self.label_Horno2.setObjectName("label_Horno2")
        self.label_Horno3 = QtWidgets.QLabel(self.centralWidget)
        self.label_Horno3.setGeometry(QtCore.QRect(10, 190, 51, 16))
        self.label_Horno3.setStyleSheet("color: white")
        self.label_Horno3.setObjectName("label_Horno3")
        self.label_Horno4 = QtWidgets.QLabel(self.centralWidget)
        self.label_Horno4.setGeometry(QtCore.QRect(10, 220, 51, 16))
        self.label_Horno4.setStyleSheet("color: white")
        self.label_Horno4.setObjectName("label_Horno4")
        self.pushButton_H1R1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H1R1.setGeometry(QtCore.QRect(80, 120, 68, 25))
        self.pushButton_H1R1.setObjectName("pushButton_H1R1")
        self.pushButton_H2R1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H2R1.setGeometry(QtCore.QRect(80, 150, 68, 25))
        self.pushButton_H2R1.setObjectName("pushButton_H2R1")
        self.pushButton_H3R1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H3R1.setGeometry(QtCore.QRect(80, 180, 68, 25))
        self.pushButton_H3R1.setObjectName("pushButton_H3R1")
        self.pushButton_H4R1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H4R1.setGeometry(QtCore.QRect(80, 210, 68, 25))
        self.pushButton_H4R1.setObjectName("pushButton_H4R1")
        self.pushButton_H4R2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H4R2.setGeometry(QtCore.QRect(150, 210, 68, 25))
        self.pushButton_H4R2.setObjectName("pushButton_H4R2")
        self.pushButton_H1R2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H1R2.setGeometry(QtCore.QRect(150, 120, 68, 25))
        self.pushButton_H1R2.setObjectName("pushButton_H1R2")
        self.pushButton_H3R2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H3R2.setGeometry(QtCore.QRect(150, 180, 68, 25))
        self.pushButton_H3R2.setObjectName("pushButton_H3R2")
        self.pushButton_H2R2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H2R2.setGeometry(QtCore.QRect(150, 150, 68, 25))
        self.pushButton_H2R2.setObjectName("pushButton_H2R2")
        self.pushButton_H4R3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H4R3.setGeometry(QtCore.QRect(220, 210, 68, 25))
        self.pushButton_H4R3.setObjectName("pushButton_H4R3")
        self.pushButton_H1R3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H1R3.setGeometry(QtCore.QRect(220, 120, 68, 25))
        self.pushButton_H1R3.setObjectName("pushButton_H1R3")
        self.pushButton_H3R3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H3R3.setGeometry(QtCore.QRect(220, 180, 68, 25))
        self.pushButton_H3R3.setObjectName("pushButton_H3R3")
        self.pushButton_H2R3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H2R3.setGeometry(QtCore.QRect(220, 150, 68, 25))
        self.pushButton_H2R3.setObjectName("pushButton_H2R3")
        self.pushButton_H4R4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H4R4.setGeometry(QtCore.QRect(290, 210, 68, 25))
        self.pushButton_H4R4.setObjectName("pushButton_H4R4")
        self.pushButton_H1R4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H1R4.setGeometry(QtCore.QRect(290, 120, 68, 25))
        self.pushButton_H1R4.setObjectName("pushButton_H1R4")
        self.pushButton_H3R4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H3R4.setGeometry(QtCore.QRect(290, 180, 68, 25))
        self.pushButton_H3R4.setObjectName("pushButton_H3R4")
        self.pushButton_H2R4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_H2R4.setGeometry(QtCore.QRect(290, 150, 68, 25))
        self.pushButton_H2R4.setObjectName("pushButton_H2R4")
        self.label_Recetas = QtWidgets.QLabel(self.centralWidget)
        self.label_Recetas.setGeometry(QtCore.QRect(10, 100, 51, 16))
        self.label_Recetas.setStyleSheet("color: white;")
        self.label_Recetas.setObjectName("label_Recetas")
        self.pushButton_MFC1_R1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC1_R1.setGeometry(QtCore.QRect(80, 240, 68, 25))
        self.pushButton_MFC1_R1.setObjectName("pushButton_MFC1_R1")
        self.pushButton_MFC4_R2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC4_R2.setGeometry(QtCore.QRect(150, 330, 68, 25))
        self.pushButton_MFC4_R2.setObjectName("pushButton_MFC4_R2")
        self.label_MFC2 = QtWidgets.QLabel(self.centralWidget)
        self.label_MFC2.setGeometry(QtCore.QRect(10, 280, 61, 16))
        self.label_MFC2.setStyleSheet("color: white")
        self.label_MFC2.setObjectName("label_MFC2")
        self.pushButton_MFC2_R4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC2_R4.setGeometry(QtCore.QRect(290, 270, 68, 25))
        self.pushButton_MFC2_R4.setObjectName("pushButton_MFC2_R4")
        self.pushButton_MFC4_R1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC4_R1.setGeometry(QtCore.QRect(80, 330, 68, 25))
        self.pushButton_MFC4_R1.setObjectName("pushButton_MFC4_R1")
        self.pushButton_MFC2_R2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC2_R2.setGeometry(QtCore.QRect(150, 270, 68, 25))
        self.pushButton_MFC2_R2.setObjectName("pushButton_MFC2_R2")
        self.pushButton_MFC3_R1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC3_R1.setGeometry(QtCore.QRect(80, 300, 68, 25))
        self.pushButton_MFC3_R1.setObjectName("pushButton_MFC3_R1")
        self.label_MFC3 = QtWidgets.QLabel(self.centralWidget)
        self.label_MFC3.setGeometry(QtCore.QRect(10, 310, 61, 16))
        self.label_MFC3.setStyleSheet("color: white")
        self.label_MFC3.setObjectName("label_MFC3")
        self.pushButton_MFC2_R1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC2_R1.setGeometry(QtCore.QRect(80, 270, 68, 25))
        self.pushButton_MFC2_R1.setObjectName("pushButton_MFC2_R1")
        self.pushButton_MFC1_R2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC1_R2.setGeometry(QtCore.QRect(150, 240, 68, 25))
        self.pushButton_MFC1_R2.setObjectName("pushButton_MFC1_R2")
        self.pushButton_MFC4_R4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC4_R4.setGeometry(QtCore.QRect(290, 330, 68, 25))
        self.pushButton_MFC4_R4.setObjectName("pushButton_MFC4_R4")
        self.pushButton_MFC2_R3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC2_R3.setGeometry(QtCore.QRect(220, 270, 68, 25))
        self.pushButton_MFC2_R3.setObjectName("pushButton_MFC2_R3")
        self.pushButton_MFC4_R3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC4_R3.setGeometry(QtCore.QRect(220, 330, 68, 25))
        self.pushButton_MFC4_R3.setObjectName("pushButton_MFC4_R3")
        self.pushButton_MFC3_R3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC3_R3.setGeometry(QtCore.QRect(220, 300, 68, 25))
        self.pushButton_MFC3_R3.setObjectName("pushButton_MFC3_R3")
        self.pushButton_MFC1_R3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC1_R3.setGeometry(QtCore.QRect(220, 240, 68, 25))
        self.pushButton_MFC1_R3.setObjectName("pushButton_MFC1_R3")
        self.pushButton_MFC3_R4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC3_R4.setGeometry(QtCore.QRect(290, 300, 68, 25))
        self.pushButton_MFC3_R4.setObjectName("pushButton_MFC3_R4")
        self.label_MFC1 = QtWidgets.QLabel(self.centralWidget)
        self.label_MFC1.setGeometry(QtCore.QRect(10, 250, 61, 16))
        self.label_MFC1.setStyleSheet("color: white")
        self.label_MFC1.setObjectName("label_MFC1")
        self.pushButton_MFC3_R2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC3_R2.setGeometry(QtCore.QRect(150, 300, 68, 25))
        self.pushButton_MFC3_R2.setObjectName("pushButton_MFC3_R2")
        self.label_MFC4 = QtWidgets.QLabel(self.centralWidget)
        self.label_MFC4.setGeometry(QtCore.QRect(10, 340, 61, 16))
        self.label_MFC4.setStyleSheet("color: white")
        self.label_MFC4.setObjectName("label_MFC4")
        self.pushButton_MFC1_R4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC1_R4.setGeometry(QtCore.QRect(290, 240, 68, 25))
        self.pushButton_MFC1_R4.setObjectName("pushButton_MFC1_R4")
        self.label_TempMantas = QtWidgets.QLabel(self.centralWidget)
        self.label_TempMantas.setGeometry(QtCore.QRect(390, 190, 61, 20))
        self.label_TempMantas.setStyleSheet("color: white")
        self.label_TempMantas.setObjectName("label_TempMantas")
        self.pushButton_TiempoR1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_TiempoR1.setGeometry(QtCore.QRect(460, 210, 68, 25))
        self.pushButton_TiempoR1.setObjectName("pushButton_TiempoR1")
        self.pushButton_TempMantasR2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_TempMantasR2.setGeometry(QtCore.QRect(530, 180, 68, 25))
        self.pushButton_TempMantasR2.setObjectName("pushButton_TempMantasR2")
        self.pushButton_TempMantasR4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_TempMantasR4.setGeometry(QtCore.QRect(670, 180, 68, 25))
        self.pushButton_TempMantasR4.setObjectName("pushButton_TempMantasR4")
        self.pushButton_TiempoR4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_TiempoR4.setGeometry(QtCore.QRect(670, 210, 68, 25))
        self.pushButton_TiempoR4.setObjectName("pushButton_TiempoR4")
        self.pushButton_TempMantasR3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_TempMantasR3.setGeometry(QtCore.QRect(600, 180, 68, 25))
        self.pushButton_TempMantasR3.setObjectName("pushButton_TempMantasR3")
        self.pushButton_TempMantasR1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_TempMantasR1.setGeometry(QtCore.QRect(460, 180, 68, 25))
        self.pushButton_TempMantasR1.setObjectName("pushButton_TempMantasR1")
        self.label_Tiempo = QtWidgets.QLabel(self.centralWidget)
        self.label_Tiempo.setGeometry(QtCore.QRect(390, 220, 51, 20))
        self.label_Tiempo.setStyleSheet("color: white")
        self.label_Tiempo.setObjectName("label_Tiempo")
        self.pushButton_TiempoR3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_TiempoR3.setGeometry(QtCore.QRect(600, 210, 68, 25))
        self.pushButton_TiempoR3.setObjectName("pushButton_TiempoR3")
        self.pushButton_TiempoR2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_TiempoR2.setGeometry(QtCore.QRect(530, 210, 68, 25))
        self.pushButton_TiempoR2.setObjectName("pushButton_TiempoR2")
        self.pushButton_MFC5_R2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC5_R2.setGeometry(QtCore.QRect(150, 360, 68, 25))
        self.pushButton_MFC5_R2.setObjectName("pushButton_MFC5_R2")
        self.pushButton_MFC5_R1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC5_R1.setGeometry(QtCore.QRect(80, 360, 68, 25))
        self.pushButton_MFC5_R1.setObjectName("pushButton_MFC5_R1")
        self.pushButton_MFC6_R4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC6_R4.setGeometry(QtCore.QRect(290, 390, 68, 25))
        self.pushButton_MFC6_R4.setObjectName("pushButton_MFC6_R4")
        self.label_MFC6 = QtWidgets.QLabel(self.centralWidget)
        self.label_MFC6.setGeometry(QtCore.QRect(10, 400, 61, 16))
        self.label_MFC6.setStyleSheet("color: white")
        self.label_MFC6.setObjectName("label_MFC6")
        self.pushButton_MFC5_R4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC5_R4.setGeometry(QtCore.QRect(290, 360, 68, 25))
        self.pushButton_MFC5_R4.setObjectName("pushButton_MFC5_R4")
        self.pushButton_MFC6_R3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC6_R3.setGeometry(QtCore.QRect(220, 390, 68, 25))
        self.pushButton_MFC6_R3.setObjectName("pushButton_MFC6_R3")
        self.pushButton_MFC5_R3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC5_R3.setGeometry(QtCore.QRect(220, 360, 68, 25))
        self.pushButton_MFC5_R3.setObjectName("pushButton_MFC5_R3")
        self.label_MFC5 = QtWidgets.QLabel(self.centralWidget)
        self.label_MFC5.setGeometry(QtCore.QRect(10, 370, 61, 16))
        self.label_MFC5.setStyleSheet("color: white")
        self.label_MFC5.setObjectName("label_MFC5")
        self.pushButton_MFC6_R2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC6_R2.setGeometry(QtCore.QRect(150, 390, 68, 25))
        self.pushButton_MFC6_R2.setObjectName("pushButton_MFC6_R2")
        self.pushButton_MFC6_R1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_MFC6_R1.setGeometry(QtCore.QRect(80, 390, 68, 25))
        self.pushButton_MFC6_R1.setObjectName("pushButton_MFC6_R1")
        self.label_Bomba = QtWidgets.QLabel(self.centralWidget)
        self.label_Bomba.setGeometry(QtCore.QRect(390, 160, 51, 20))
        self.label_Bomba.setStyleSheet("color: white")
        self.label_Bomba.setObjectName("label_Bomba")
        self.pushButton_Solenoide_R4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Solenoide_R4.setGeometry(QtCore.QRect(670, 120, 68, 25))
        self.pushButton_Solenoide_R4.setObjectName("pushButton_Solenoide_R4")
        self.pushButton_Solenoide_R1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Solenoide_R1.setGeometry(QtCore.QRect(460, 120, 68, 25))
        self.pushButton_Solenoide_R1.setObjectName("pushButton_Solenoide_R1")
        self.label_Solenoide = QtWidgets.QLabel(self.centralWidget)
        self.label_Solenoide.setGeometry(QtCore.QRect(390, 130, 61, 20))
        self.label_Solenoide.setStyleSheet("color: white")
        self.label_Solenoide.setObjectName("label_Solenoide")
        self.pushButton_Bomba_R2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Bomba_R2.setGeometry(QtCore.QRect(530, 150, 68, 25))
        self.pushButton_Bomba_R2.setObjectName("pushButton_Bomba_R2")
        self.pushButton_Bomba_R1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Bomba_R1.setGeometry(QtCore.QRect(460, 150, 68, 25))
        self.pushButton_Bomba_R1.setObjectName("pushButton_Bomba_R1")
        self.pushButton_Bomba_R3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Bomba_R3.setGeometry(QtCore.QRect(600, 150, 68, 25))
        self.pushButton_Bomba_R3.setObjectName("pushButton_Bomba_R3")
        self.pushButton_Solenoide_R2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Solenoide_R2.setGeometry(QtCore.QRect(530, 120, 68, 25))
        self.pushButton_Solenoide_R2.setObjectName("pushButton_Solenoide_R2")
        self.pushButton_Solenoide_R3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Solenoide_R3.setGeometry(QtCore.QRect(600, 120, 68, 25))
        self.pushButton_Solenoide_R3.setObjectName("pushButton_Solenoide_R3")
        self.pushButton_Bomba_R4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Bomba_R4.setGeometry(QtCore.QRect(670, 150, 68, 25))
        self.pushButton_Bomba_R4.setObjectName("pushButton_Bomba_R4")
        self.pushButton_Receta4_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Receta4_2.setGeometry(QtCore.QRect(670, 90, 68, 25))
        self.pushButton_Receta4_2.setStyleSheet("")
        self.pushButton_Receta4_2.setObjectName("pushButton_Receta4_2")
        self.pushButton_Receta1_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Receta1_2.setGeometry(QtCore.QRect(460, 90, 68, 25))
        self.pushButton_Receta1_2.setStyleSheet("")
        self.pushButton_Receta1_2.setObjectName("pushButton_Receta1_2")
        self.pushButton_Receta3_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Receta3_2.setGeometry(QtCore.QRect(600, 90, 68, 25))
        self.pushButton_Receta3_2.setStyleSheet("")
        self.pushButton_Receta3_2.setObjectName("pushButton_Receta3_2")
        self.label_Recetas_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_Recetas_2.setGeometry(QtCore.QRect(390, 100, 51, 16))
        self.label_Recetas_2.setStyleSheet("color: white;")
        self.label_Recetas_2.setObjectName("label_Recetas_2")
        self.pushButton_Receta2_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Receta2_2.setGeometry(QtCore.QRect(530, 90, 68, 25))
        self.pushButton_Receta2_2.setStyleSheet("")
        self.pushButton_Receta2_2.setObjectName("pushButton_Receta2_2")

        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.pushButton_Home = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Home.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.pushButton_Home.setStyleSheet("background-color: #222222; color:white; font-size: 22pt;")
        self.pushButton_Home.setIcon(QtGui.QIcon('../images/home.png'))
        self.pushButton_Home.setIconSize(QtCore.QSize(31,31))

        self.pushButton_Back = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Back.setGeometry(QtCore.QRect(73, 0, 71, 71))
        self.pushButton_Back.setStyleSheet("background-color: #222222; color: #222222; font-size: 22pt;")
        self.pushButton_Back.setIcon(QtGui.QIcon('../images/back.png'))
        self.pushButton_Back.setIconSize(QtCore.QSize(31,31))

        self.buttonTime= QtWidgets.QPushButton(self.centralWidget)
        self.buttonTime.setGeometry(QtCore.QRect(550, 25, 90, 30))
        self.buttonTime.setObjectName("pushButtonTime")
        self.buttonTime.setStyleSheet("background-color:#2F4F4F; color: white")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quirema"))
        self.label.setText(_translate("MainWindow", "                            Quirema                   Recetas hoja 2"))
        self.pushButton_Receta1.setText(_translate("MainWindow", "5"))
        self.pushButton_Receta1.setStyleSheet("background-color:black;color:white")

        self.pushButton_Receta2.setText(_translate("MainWindow", "6"))
        self.pushButton_Receta2.setStyleSheet("background-color:black;color:white")

        self.pushButton_Receta3.setText(_translate("MainWindow", "7"))
        self.pushButton_Receta3.setStyleSheet("background-color:black;color:white")

        self.pushButton_Receta4.setText(_translate("MainWindow", "8"))
        self.pushButton_Receta4.setStyleSheet("background-color:black;color:white")

        self.label_Horno1.setText(_translate("MainWindow", "Horno 1"))
        self.label_Horno2.setText(_translate("MainWindow", "Horno 2"))
        self.label_Horno3.setText(_translate("MainWindow", "Horno 3"))
        self.label_Horno4.setText(_translate("MainWindow", "Horno 4"))
        self.pushButton_H1R1.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H2R1.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H3R1.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H4R1.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H4R2.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H1R2.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H3R2.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H2R2.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H4R3.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H1R3.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H3R3.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H2R3.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H4R4.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H1R4.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H3R4.setText(_translate("MainWindow", "0.0"))
        self.pushButton_H2R4.setText(_translate("MainWindow", "0.0"))
        self.label_Recetas.setText(_translate("MainWindow", "Recetas"))
        self.pushButton_MFC1_R1.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC4_R2.setText(_translate("MainWindow", "0.0"))
        self.label_MFC2.setText(_translate("MainWindow", "C. Flujo 2"))
        self.pushButton_MFC2_R4.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC4_R1.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC2_R2.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC3_R1.setText(_translate("MainWindow", "0.0"))
        self.label_MFC3.setText(_translate("MainWindow", "C. Flujo 3"))
        self.pushButton_MFC2_R1.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC1_R2.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC4_R4.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC2_R3.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC4_R3.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC3_R3.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC1_R3.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC3_R4.setText(_translate("MainWindow", "0.0"))
        self.label_MFC1.setText(_translate("MainWindow", "C. Flujo 1"))
        self.pushButton_MFC3_R2.setText(_translate("MainWindow", "0.0"))
        self.label_MFC4.setText(_translate("MainWindow", "C. Flujo 4"))
        self.pushButton_MFC1_R4.setText(_translate("MainWindow", "0.0"))
        self.label_TempMantas.setText(_translate("MainWindow", "T. Mantas"))
        self.pushButton_TiempoR1.setText(_translate("MainWindow", "0.0"))
        self.pushButton_TempMantasR2.setText(_translate("MainWindow", "0.0"))
        self.pushButton_TempMantasR4.setText(_translate("MainWindow", "0.0"))
        self.pushButton_TiempoR4.setText(_translate("MainWindow", "0.0"))
        self.pushButton_TempMantasR3.setText(_translate("MainWindow", "0.0"))
        self.pushButton_TempMantasR1.setText(_translate("MainWindow", "0.0"))
        self.label_Tiempo.setText(_translate("MainWindow", "Tiempo"))
        self.pushButton_TiempoR3.setText(_translate("MainWindow", "0.0"))
        self.pushButton_TiempoR2.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC5_R2.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC5_R1.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC6_R4.setText(_translate("MainWindow", "0.0"))
        self.label_MFC6.setText(_translate("MainWindow", "C. Flujo 6"))
        self.pushButton_MFC5_R4.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC6_R3.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC5_R3.setText(_translate("MainWindow", "0.0"))
        self.label_MFC5.setText(_translate("MainWindow", "C. Flujo 5"))
        self.pushButton_MFC6_R2.setText(_translate("MainWindow", "0.0"))
        self.pushButton_MFC6_R1.setText(_translate("MainWindow", "0.0"))
        self.label_Bomba.setText(_translate("MainWindow", "Bomba"))
        self.pushButton_Solenoide_R4.setText(_translate("MainWindow", "0.0"))
        self.pushButton_Solenoide_R1.setText(_translate("MainWindow", "0.0"))
        self.label_Solenoide.setText(_translate("MainWindow", "Solenoide"))
        self.pushButton_Bomba_R2.setText(_translate("MainWindow", "0.0"))
        self.pushButton_Bomba_R1.setText(_translate("MainWindow", "0.0"))
        self.pushButton_Bomba_R3.setText(_translate("MainWindow", "0.0"))
        self.pushButton_Solenoide_R2.setText(_translate("MainWindow", "0.0"))
        self.pushButton_Solenoide_R3.setText(_translate("MainWindow", "0.0"))
        self.pushButton_Bomba_R4.setText(_translate("MainWindow", "0.0"))
        self.pushButton_Receta4_2.setText(_translate("MainWindow", "8"))
        self.pushButton_Receta4_2.setStyleSheet("background-color:black;color:white")

        self.pushButton_Receta1_2.setText(_translate("MainWindow", "5"))
        self.pushButton_Receta1_2.setStyleSheet("background-color:black;color:white")

        self.pushButton_Receta3_2.setText(_translate("MainWindow", "7"))
        self.pushButton_Receta3_2.setStyleSheet("background-color:black;color:white")

        self.label_Recetas_2.setText(_translate("MainWindow", "Recetas"))
        self.pushButton_Receta2_2.setText(_translate("MainWindow", "6"))
        self.pushButton_Receta2_2.setStyleSheet("background-color:black;color:white")

        self.addActionButtons()

        self.t = threading.Thread(target = self.actualizaValoresTimer)
        self.t.IsBackground = True;
        self.t.start()

    def addActionButtons(self):
        self.pushButton_Home.clicked.connect(self.home)
        self.pushButton_Back.clicked.connect(self.back)

        # Elementos receta 1
        self.pushButton_H1R1.clicked.connect(lambda: self.displayCalculadora("5","horno1"))
        self.pushButton_H2R1.clicked.connect(lambda: self.displayCalculadora("5","horno2"))
        self.pushButton_H3R1.clicked.connect(lambda: self.displayCalculadora("5","horno3"))
        self.pushButton_H4R1.clicked.connect(lambda: self.displayCalculadora("5","horno4"))

        self.pushButton_MFC1_R1.clicked.connect(lambda: self.displayCalculadora("5","MFC1"))
        self.pushButton_MFC2_R1.clicked.connect(lambda: self.displayCalculadora("5","MFC2"))
        self.pushButton_MFC3_R1.clicked.connect(lambda: self.displayCalculadora("5","MFC3"))
        self.pushButton_MFC4_R1.clicked.connect(lambda: self.displayCalculadora("5","MFC4"))
        self.pushButton_MFC5_R1.clicked.connect(lambda: self.displayCalculadora("5","MFC5"))
        self.pushButton_MFC6_R1.clicked.connect(lambda: self.displayCalculadora("5","MFC6"))

        self.pushButton_Solenoide_R1.clicked.connect(lambda: self.displayCalculadora("5","Solenoide"))
        self.pushButton_Bomba_R1.clicked.connect(lambda: self.displayCalculadora("5","Bomba"))
        self.pushButton_TempMantasR1.clicked.connect(lambda: self.displayCalculadora("5","TempMantas"))
        self.pushButton_TiempoR1.clicked.connect(lambda: self.displayCalculadora("5","Tiempo"))

        # Elementos receta 2
        self.pushButton_H1R2.clicked.connect(lambda: self.displayCalculadora("6","horno1"))
        self.pushButton_H2R2.clicked.connect(lambda: self.displayCalculadora("6","horno2"))
        self.pushButton_H3R2.clicked.connect(lambda: self.displayCalculadora("6","horno3"))
        self.pushButton_H4R2.clicked.connect(lambda: self.displayCalculadora("6","horno4"))
        
        self.pushButton_MFC1_R2.clicked.connect(lambda: self.displayCalculadora("6","MFC1"))
        self.pushButton_MFC2_R2.clicked.connect(lambda: self.displayCalculadora("6","MFC2"))
        self.pushButton_MFC3_R2.clicked.connect(lambda: self.displayCalculadora("6","MFC3"))
        self.pushButton_MFC4_R2.clicked.connect(lambda: self.displayCalculadora("6","MFC4"))
        self.pushButton_MFC5_R2.clicked.connect(lambda: self.displayCalculadora("6","MFC5"))
        self.pushButton_MFC6_R2.clicked.connect(lambda: self.displayCalculadora("6","MFC6"))

        self.pushButton_Solenoide_R2.clicked.connect(lambda: self.displayCalculadora("6","Solenoide"))
        self.pushButton_Bomba_R2.clicked.connect(lambda: self.displayCalculadora("6","Bomba"))
        self.pushButton_TempMantasR2.clicked.connect(lambda: self.displayCalculadora("6","TempMantas"))
        self.pushButton_TiempoR2.clicked.connect(lambda: self.displayCalculadora("6","Tiempo"))


        # Elementos receta 3
        self.pushButton_H1R3.clicked.connect(lambda: self.displayCalculadora("7","horno1"))
        self.pushButton_H2R3.clicked.connect(lambda: self.displayCalculadora("7","horno2"))
        self.pushButton_H3R3.clicked.connect(lambda: self.displayCalculadora("7","horno3"))
        self.pushButton_H4R3.clicked.connect(lambda: self.displayCalculadora("7","horno4"))
        
        self.pushButton_MFC1_R3.clicked.connect(lambda: self.displayCalculadora("7","MFC1"))
        self.pushButton_MFC2_R3.clicked.connect(lambda: self.displayCalculadora("7","MFC2"))
        self.pushButton_MFC3_R3.clicked.connect(lambda: self.displayCalculadora("7","MFC3"))
        self.pushButton_MFC4_R3.clicked.connect(lambda: self.displayCalculadora("7","MFC4"))
        self.pushButton_MFC5_R3.clicked.connect(lambda: self.displayCalculadora("7","MFC5"))
        self.pushButton_MFC6_R3.clicked.connect(lambda: self.displayCalculadora("7","MFC6"))

        self.pushButton_Solenoide_R3.clicked.connect(lambda: self.displayCalculadora("7","Solenoide"))
        self.pushButton_Bomba_R3.clicked.connect(lambda: self.displayCalculadora("7","Bomba"))
        self.pushButton_TempMantasR3.clicked.connect(lambda: self.displayCalculadora("7","TempMantas"))
        self.pushButton_TiempoR3.clicked.connect(lambda: self.displayCalculadora("7","Tiempo"))
        
        
        # Elementos receta 4
        self.pushButton_H1R4.clicked.connect(lambda: self.displayCalculadora("8","horno1"))
        self.pushButton_H2R4.clicked.connect(lambda: self.displayCalculadora("8","horno2"))
        self.pushButton_H3R4.clicked.connect(lambda: self.displayCalculadora("8","horno3"))
        self.pushButton_H4R4.clicked.connect(lambda: self.displayCalculadora("8","horno4"))
        
        self.pushButton_MFC1_R4.clicked.connect(lambda: self.displayCalculadora("8","MFC1"))
        self.pushButton_MFC2_R4.clicked.connect(lambda: self.displayCalculadora("8","MFC2"))
        self.pushButton_MFC3_R4.clicked.connect(lambda: self.displayCalculadora("8","MFC3"))
        self.pushButton_MFC4_R4.clicked.connect(lambda: self.displayCalculadora("8","MFC4"))
        self.pushButton_MFC5_R4.clicked.connect(lambda: self.displayCalculadora("8","MFC5"))
        self.pushButton_MFC6_R4.clicked.connect(lambda: self.displayCalculadora("8","MFC6"))
        
        self.pushButton_Solenoide_R4.clicked.connect(lambda: self.displayCalculadora("8","Solenoide"))
        self.pushButton_Bomba_R4.clicked.connect(lambda: self.displayCalculadora("8","Bomba"))
        self.pushButton_TempMantasR4.clicked.connect(lambda: self.displayCalculadora("8","TempMantas"))
        self.pushButton_TiempoR4.clicked.connect(lambda: self.displayCalculadora("8","Tiempo"))

    def home(self):
        self.flag_DesactivaVista = True
        self.home = Home.Ui_MainWindow()
        self.home.setupUi(self.MainWindow, self.s, self.sBomba)

    def back(self):
        self.flag_DesactivaVista = True
        self.sectionVector = [False,False,False,True,False,False]
        self.recetas1_Window = recetas1.Ui_MainWindow()
        self.recetas1_Window.setupUi(self.MainWindow, self.sectionVector, self.s, self.sBomba)

    def displayCalculadora(self, receta, equipoSeleccionado):
        self.MainWindow.setEnabled(False)
        MainWindow = QtWidgets.QMainWindow()
        self.equipoSeleccionado = equipoSeleccionado
        self.receta = receta

        self.calculadora = calculadora2.Ui_MainWindow()
        self.sectionVector = [False,False,False,True,False,False]
        self.calculadora.setupUi_recetas(MainWindow, receta, equipoSeleccionado, self.sectionVector, self.MainWindow, 'hoja2')
        MainWindow.show()

    def actualizaValoresTimer(self):
        global variableAModificar, setValueFromCalculadora

        while True:
            try:
                if(self.flag_DesactivaVista == True):
                    break
                recetas = self.instanciaModbus.readRegister_Recetas('hoja2')         

                print(recetas)

                # Elementos receta 1
                h1r1String = self.decimalString(str(int(recetas[0],16))) 
                self.pushButton_H1R1.setText(h1r1String)
                time.sleep(0.005)

                h2r1String = self.decimalString(str(int(recetas[1],16))) 
                self.pushButton_H2R1.setText(h2r1String)
                time.sleep(0.005)

                h3r1String = self.decimalString(str(int(recetas[2],16))) 
                self.pushButton_H3R1.setText(h3r1String)
                time.sleep(0.005)

                h4r1String = self.decimalString(str(int(recetas[3],16))) 
                self.pushButton_H4R1.setText(h4r1String)
                time.sleep(0.005)

                MFC1_R1String = self.decimalString(str(int(recetas[4],16))) 
                self.pushButton_MFC1_R1.setText(MFC1_R1String)
                time.sleep(0.005)

                MFC2_R1String = self.decimalString(str(int(recetas[5],16))) 
                self.pushButton_MFC2_R1.setText(MFC2_R1String)
                time.sleep(0.005)

                MFC3_R1String = self.decimalString(str(int(recetas[6],16))) 
                self.pushButton_MFC3_R1.setText(MFC3_R1String)
                time.sleep(0.005)

                MFC4_R1String = self.decimalString(str(int(recetas[7],16))) 
                self.pushButton_MFC4_R1.setText(MFC4_R1String)
                time.sleep(0.005)

                MFC5_R1String = self.decimalString(str(int(recetas[8],16))) 
                self.pushButton_MFC5_R1.setText(MFC5_R1String)
                time.sleep(0.005)

                MFC6_R1String = self.decimalString(str(int(recetas[9],16))) 
                self.pushButton_MFC6_R1.setText(MFC6_R1String)
                time.sleep(0.005)

                Solenoide_R1String = self.decimalString(str(int(recetas[10],16))) 
                self.pushButton_Solenoide_R1.setText(Solenoide_R1String)
                time.sleep(0.005)

                bomba_R1String = self.decimalString(str(int(recetas[11],16)))
                self.pushButton_Bomba_R1.setText(bomba_R1String)
                time.sleep(0.005)

                tempMantas_R1String = self.decimalString(str(int(recetas[12],16)))
                self.pushButton_TempMantasR1.setText(tempMantas_R1String)
                time.sleep(0.005)

                tiempos_R1String = self.decimalString(str(int(recetas[13],16)))
                self.pushButton_TiempoR1.setText(tiempos_R1String)
                time.sleep(0.005)


                # Elementos receta 2
                h1r2String = self.decimalString(str(int(recetas[14],16))) 
                self.pushButton_H1R2.setText(h1r2String)
                time.sleep(0.005)

                h2r2String = self.decimalString(str(int(recetas[15],16))) 
                self.pushButton_H2R2.setText(h2r2String)
                time.sleep(0.005)

                h3r2String = self.decimalString(str(int(recetas[16],16))) 
                self.pushButton_H3R2.setText(h3r2String)
                time.sleep(0.005)

                h4r2String = self.decimalString(str(int(recetas[17],16))) 
                self.pushButton_H4R2.setText(h4r2String)
                time.sleep(0.005)
                
                MFC1_R2String = self.decimalString(str(int(recetas[18],16))) 
                self.pushButton_MFC1_R2.setText(MFC1_R2String)
                time.sleep(0.005)

                MFC2_R2String = self.decimalString(str(int(recetas[19],16))) 
                self.pushButton_MFC2_R2.setText(MFC2_R2String)
                time.sleep(0.005)

                MFC3_R2String = self.decimalString(str(int(recetas[20],16))) 
                self.pushButton_MFC3_R2.setText(MFC3_R2String)
                time.sleep(0.005)

                MFC4_R2String = self.decimalString(str(int(recetas[21],16))) 
                self.pushButton_MFC4_R2.setText(MFC4_R2String)
                time.sleep(0.005)

                MFC5_R2String = self.decimalString(str(int(recetas[22],16))) 
                self.pushButton_MFC5_R2.setText(MFC5_R2String)
                time.sleep(0.005)

                MFC6_R2String = self.decimalString(str(int(recetas[23],16))) 
                self.pushButton_MFC6_R2.setText(MFC6_R2String)
                time.sleep(0.005)

                solenoide_R2String = self.decimalString(str(int(recetas[24],16))) 
                self.pushButton_Solenoide_R2.setText(solenoide_R2String)
                time.sleep(0.005)

                bomba_R2String = self.decimalString(str(int(recetas[25],16))) 
                self.pushButton_Bomba_R2.setText(bomba_R2String)
                time.sleep(0.005)

                tempMantas_R2String = self.decimalString(str(int(recetas[26],16)))
                self.pushButton_TempMantasR2.setText(tempMantas_R2String)
                time.sleep(0.005)

                tiempo_R2String = self.decimalString(str(int(recetas[27],16)))
                self.pushButton_TiempoR2.setText(tiempo_R2String)
                time.sleep(0.005)


                # Elementos receta 3
                h1r3String = self.decimalString(str(int(recetas[28],16))) 
                self.pushButton_H1R3.setText(h1r3String)
                time.sleep(0.005)

                h2r3String = self.decimalString(str(int(recetas[29],16)))
                self.pushButton_H2R3.setText(h2r3String)
                time.sleep(0.005)

                h3r3String = self.decimalString(str(int(recetas[30],16)))
                self.pushButton_H3R3.setText(h3r3String)
                time.sleep(0.005)

                h4r3String = self.decimalString(str(int(recetas[31],16)))
                self.pushButton_H4R3.setText(h4r3String)
                time.sleep(0.005)
                
                MFC1_R3String = self.decimalString(str(int(recetas[32],16)))
                self.pushButton_MFC1_R3.setText(MFC1_R3String)
                time.sleep(0.005)

                MFC2_R3String = self.decimalString(str(int(recetas[33],16)))
                self.pushButton_MFC2_R3.setText(MFC2_R3String)
                time.sleep(0.005)

                MFC3_R3String = self.decimalString(str(int(recetas[34],16)))
                self.pushButton_MFC3_R3.setText(MFC3_R3String)
                time.sleep(0.005)

                MFC4_R3String = self.decimalString(str(int(recetas[35],16)))
                self.pushButton_MFC4_R3.setText(MFC4_R3String)
                time.sleep(0.005)

                MFC5_R3String = self.decimalString(str(int(recetas[36],16)))
                self.pushButton_MFC5_R3.setText(MFC5_R3String)
                time.sleep(0.005)

                MFC6_R3String = self.decimalString(str(int(recetas[37],16)))
                self.pushButton_MFC6_R3.setText(MFC6_R3String)
                time.sleep(0.005)

                solenoide_R3String = self.decimalString(str(int(recetas[38],16)))
                self.pushButton_Solenoide_R3.setText(solenoide_R3String)
                time.sleep(0.005)

                bomba_R3String = self.decimalString(str(int(recetas[39],16)))
                self.pushButton_Bomba_R3.setText(bomba_R3String)
                time.sleep(0.005)

                tempMantas_R3String = self.decimalString(str(int(recetas[40],16)))
                self.pushButton_TempMantasR3.setText(tempMantas_R3String)
                time.sleep(0.005)

                tiempo_R3String = self.decimalString(str(int(recetas[41],16)))
                self.pushButton_TiempoR3.setText(tiempo_R3String)
                time.sleep(0.005)
                
                
                # Elementos receta 4
                h1r4String = self.decimalString(str(int(recetas[42],16))) 
                self.pushButton_H1R4.setText(h1r4String)
                time.sleep(0.005)

                h2r4String = self.decimalString(str(int(recetas[43],16))) 
                self.pushButton_H2R4.setText(h2r4String)
                time.sleep(0.005)

                h3r4String = self.decimalString(str(int(recetas[44],16))) 
                self.pushButton_H3R4.setText(h3r4String)
                time.sleep(0.005)

                h4r4String = self.decimalString(str(int(recetas[45],16))) 
                self.pushButton_H4R4.setText(h4r4String)
                time.sleep(0.005)
                
                MFC1_R4String = self.decimalString(str(int(recetas[46],16)))
                self.pushButton_MFC1_R4.setText(MFC1_R4String)
                time.sleep(0.005)

                MFC2_R4String = self.decimalString(str(int(recetas[47],16)))
                self.pushButton_MFC2_R4.setText(MFC2_R4String)
                time.sleep(0.005)

                MFC3_R4String = self.decimalString(str(int(recetas[48],16)))
                self.pushButton_MFC3_R4.setText(MFC3_R4String)
                time.sleep(0.005)

                MFC4_R4String = self.decimalString(str(int(recetas[49],16)))
                self.pushButton_MFC4_R4.setText(MFC4_R4String)
                time.sleep(0.005)

                MFC5_R4String = self.decimalString(str(int(recetas[50],16)))
                self.pushButton_MFC5_R4.setText(MFC5_R4String)
                time.sleep(0.005)

                MFC6_R4String = self.decimalString(str(int(recetas[51],16)))
                self.pushButton_MFC6_R4.setText(MFC6_R4String)
                time.sleep(0.005)
                
                solenoide_R4String = self.decimalString(str(int(recetas[52],16)))
                self.pushButton_Solenoide_R4.setText(solenoide_R4String)
                time.sleep(0.005)

                bomba_R4String = self.decimalString(str(int(recetas[53],16)))
                self.pushButton_Bomba_R4.setText(bomba_R4String)
                time.sleep(0.005)

                tempMantas_R4String = self.decimalString(str(int(recetas[54],16)))
                self.pushButton_TempMantasR4.setText(tempMantas_R4String)
                time.sleep(0.005)

                tiempo_R4String = self.decimalString(str(int(recetas[55],16)))
                self.pushButton_TiempoR4.setText(tiempo_R4String)
                time.sleep(0.005)

                hora = time.strftime("%H:%M:%S")

                try:
                    self.buttonTime.setText(hora)
                except:
                    pass

                if (setValueFromCalculadora == True):
                    setValueFromCalculadora = False
                    try:
                        self.instanciaModbus.writeValuesRecetas(self.receta, self.equipoSeleccionado, float(variableAModificar))    
                    except:
                        pass            
                time.sleep(0.1)
            
            except:
                pass

    def decimalString(self, stringValue):
        stringValueReturn = stringValue
        if len(stringValueReturn)==1:
            stringValueReturn = '0.' + stringValueReturn
        else:   
            stringValueReturn = stringValueReturn[0:(len(stringValueReturn)-1)] + '.' + stringValueReturn[len(stringValueReturn)-1]
        return stringValueReturn

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet('QMainWindow{background-color: qlineargradient(spread:reflect, x1:1, y1:0, x2:0, y2:1, stop:0 rgba(0, 64, 128, 255), stop:1 rgba(0, 0, 0, 255)); border:2px solid black;}')
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
