# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_setUpBomba.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import calculadora2
from PyQt5.QtCore import QPoint

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, socketBomba):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(336, 407)
        
        qPoint = QPoint(280,60)
        MainWindow.move(qPoint)

        self.sBomba = socketBomba

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 123, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 102, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 123, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 102, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 123, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 102, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 82, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 64, 128, 255), stop:1 rgba(0, 0, 0, 255))")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralWidget.setAutoFillBackground(False)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.label_Units = QtWidgets.QLabel(self.centralWidget)
        self.label_Units.setGeometry(QtCore.QRect(40, 90, 81, 16))
        self.label_Units.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_Units.setObjectName("label_Units")
        self.label_Diameter = QtWidgets.QLabel(self.centralWidget)
        self.label_Diameter.setGeometry(QtCore.QRect(40, 120, 81, 16))
        self.label_Diameter.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_Diameter.setObjectName("label_Diameter")
        self.label_Rate = QtWidgets.QLabel(self.centralWidget)
        self.label_Rate.setGeometry(QtCore.QRect(40, 150, 81, 16))
        self.label_Rate.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_Rate.setObjectName("label_Rate")
        self.label_Volume = QtWidgets.QLabel(self.centralWidget)
        self.label_Volume.setGeometry(QtCore.QRect(40, 180, 81, 16))
        self.label_Volume.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_Volume.setObjectName("label_Volume")
        self.label_title = QtWidgets.QLabel(self.centralWidget)
        self.label_title.setGeometry(QtCore.QRect(100, 30, 131, 31))
        self.label_title.setAutoFillBackground(False)
        self.label_title.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_title.setObjectName("label_title")
        self.startButton = QtWidgets.QPushButton(self.centralWidget)
        self.startButton.setGeometry(QtCore.QRect(20, 290, 71, 32))
        self.startButton.setStyleSheet("background:none")
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(self.centralWidget)
        self.stopButton.setGeometry(QtCore.QRect(90, 290, 71, 32))
        self.stopButton.setStyleSheet("background:none")
        self.stopButton.setObjectName("stopButton")
        self.pauseButton = QtWidgets.QPushButton(self.centralWidget)
        self.pauseButton.setGeometry(QtCore.QRect(160, 290, 71, 32))
        self.pauseButton.setStyleSheet("background:none")
        self.pauseButton.setObjectName("pauseButton")
        self.restartButton = QtWidgets.QPushButton(self.centralWidget)
        self.restartButton.setGeometry(QtCore.QRect(230, 290, 71, 32))
        self.restartButton.setStyleSheet("background:none")
        self.restartButton.setObjectName("restartButton")
        self.label_Delay = QtWidgets.QLabel(self.centralWidget)
        self.label_Delay.setGeometry(QtCore.QRect(40, 210, 81, 16))
        self.label_Delay.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_Delay.setObjectName("label_Delay")
        self.label_Time = QtWidgets.QLabel(self.centralWidget)
        self.label_Time.setGeometry(QtCore.QRect(40, 240, 81, 16))
        self.label_Time.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_Time.setObjectName("label_Time")
        self.UnitsButton = QtWidgets.QPushButton(self.centralWidget)
        self.UnitsButton.setGeometry(QtCore.QRect(150, 80, 71, 32))
        self.UnitsButton.setStyleSheet("background:none")
        self.UnitsButton.setObjectName("UnitsButton")
        self.DiameterButton = QtWidgets.QPushButton(self.centralWidget)
        self.DiameterButton.setGeometry(QtCore.QRect(150, 110, 71, 32))
        self.DiameterButton.setStyleSheet("background:none")
        self.DiameterButton.setObjectName("DiameterButton")
        self.rateButton = QtWidgets.QPushButton(self.centralWidget)
        self.rateButton.setGeometry(QtCore.QRect(150, 140, 71, 32))
        self.rateButton.setStyleSheet("background:none")
        self.rateButton.setObjectName("rateButton")
        self.VolumeButton = QtWidgets.QPushButton(self.centralWidget)
        self.VolumeButton.setGeometry(QtCore.QRect(150, 170, 71, 32))
        self.VolumeButton.setStyleSheet("background:none")
        self.VolumeButton.setObjectName("VolumeButton")
        self.DelayButton = QtWidgets.QPushButton(self.centralWidget)
        self.DelayButton.setGeometry(QtCore.QRect(150, 200, 71, 32))
        self.DelayButton.setStyleSheet("background:none")
        self.DelayButton.setObjectName("DelayButton")
        self.TimeButton = QtWidgets.QPushButton(self.centralWidget)
        self.TimeButton.setGeometry(QtCore.QRect(150, 230, 71, 32))
        self.TimeButton.setStyleSheet("background:none")
        self.TimeButton.setObjectName("TimeButton")
        self.label_unitsUnits = QtWidgets.QLabel(self.centralWidget)
        self.label_unitsUnits.setGeometry(QtCore.QRect(230, 90, 61, 16))
        self.label_unitsUnits.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_unitsUnits.setObjectName("label_unitsUnits")
        self.label_UnitsDiameter = QtWidgets.QLabel(self.centralWidget)
        self.label_UnitsDiameter.setGeometry(QtCore.QRect(230, 120, 61, 16))
        self.label_UnitsDiameter.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_UnitsDiameter.setObjectName("label_UnitsDiameter")
        self.label_UnitsRate = QtWidgets.QLabel(self.centralWidget)
        self.label_UnitsRate.setGeometry(QtCore.QRect(230, 150, 61, 16))
        self.label_UnitsRate.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_UnitsRate.setObjectName("label_UnitsRate")
        self.label_UnitsVolume = QtWidgets.QLabel(self.centralWidget)
        self.label_UnitsVolume.setGeometry(QtCore.QRect(230, 180, 61, 16))
        self.label_UnitsVolume.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_UnitsVolume.setObjectName("label_UnitsVolume")
        self.label_UnitsDelay = QtWidgets.QLabel(self.centralWidget)
        self.label_UnitsDelay.setGeometry(QtCore.QRect(230, 210, 61, 16))
        self.label_UnitsDelay.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_UnitsDelay.setObjectName("label_UnitsDelay")
        self.label_UnitsTime = QtWidgets.QLabel(self.centralWidget)
        self.label_UnitsTime.setGeometry(QtCore.QRect(230, 240, 61, 16))
        self.label_UnitsTime.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_UnitsTime.setObjectName("label_UnitsTime")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 336, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quirema"))
        self.label_Units.setText(_translate("MainWindow", "Units:"))
        self.label_Diameter.setText(_translate("MainWindow", "Diameter:"))
        self.label_Rate.setText(_translate("MainWindow", "Rate:"))
        self.label_Volume.setText(_translate("MainWindow", "Volume:"))
        self.label_title.setText(_translate("MainWindow", "Set Up Bomba"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.restartButton.setText(_translate("MainWindow", "Restart"))
        self.label_Delay.setText(_translate("MainWindow", "Delay:"))
        self.label_Time.setText(_translate("MainWindow", "Time:"))
        self.UnitsButton.setText(_translate("MainWindow", "0.0"))
        self.DiameterButton.setText(_translate("MainWindow", "0.0"))
        self.rateButton.setText(_translate("MainWindow", "0.0"))
        self.VolumeButton.setText(_translate("MainWindow", "0.0"))
        self.DelayButton.setText(_translate("MainWindow", "0.0"))
        self.TimeButton.setText(_translate("MainWindow", "0.0"))
        self.label_unitsUnits.setText(_translate("MainWindow", "mL/min"))
        self.label_UnitsDiameter.setText(_translate("MainWindow", "mm"))
        self.label_UnitsRate.setText(_translate("MainWindow", "mL/min"))
        self.label_UnitsVolume.setText(_translate("MainWindow", "mm"))
        self.label_UnitsDelay.setText(_translate("MainWindow", "min"))
        self.label_UnitsTime.setText(_translate("MainWindow", "min"))

        self.addActionButtons()

    def addActionButtons(self):
        self.UnitsButton.clicked.connect(lambda: self.displayCalculadora("Units"))
        self.DiameterButton.clicked.connect(lambda: self.displayCalculadora("Diameter"))
        self.rateButton.clicked.connect(lambda: self.displayCalculadora("Rate"))
        self.VolumeButton.clicked.connect(lambda: self.displayCalculadora("Volume"))
        self.DelayButton.clicked.connect(lambda: self.displayCalculadora("Delay"))
        self.TimeButton.clicked.connect(lambda: self.displayCalculadora("Time"))

        self.startButton.clicked.connect(self.startBomba)
        self.stopButton.clicked.connect(self.stopBomba)
        self.pauseButton.clicked.connect(self.pauseBomba)
        self.restartButton.clicked.connect(self.restartBomba)

    def displayCalculadora(self, variableBomba):
        sectionVector = [False,False,False,False,False,True]
        self.calculadora = calculadora2.Ui_MainWindow()
        socketBomba = "socketBomba"
        self.calculadora.setUp_Bomba(self.MainWindow, sectionVector, variableBomba, socketBomba)
        print("variable=", variableBomba)

    def startBomba(self):

        try:
            comando = bytes('start\r\n','UTF-8')
            self.sBomba.write(comando)
            lectura = self.sBomba.readline()
            print("leido start", lectura)
        except:
            pass

    def stopBomba(self):
        try:
            comando = bytes('stop\r\n','UTF-8')
            self.sBomba.write(comando)
            lectura = self.sBomba.readline()
            print("leido start", lectura)
        except:
            pass

    def pauseBomba(self):
        try:
            comando = bytes('pause\r\n','UTF-8')
            self.sBomba.write(comando)
            lectura = self.sBomba.readline()
            print("leido start", lectura)
        except:
            pass

    def restartBomba(self):
        try:
            comando = bytes('restart\r\n','UTF-8')
            self.sBomba.write(comando)
            lectura = self.sBomba.readline()
            print("leido start", lectura)
        except:
            pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
