# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_setUpBomba.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QPoint

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(370, 305)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 123, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 102, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 123, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 102, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 123, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 102, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 1.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 64, 128))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 82, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 64, 128, 255), stop:1 rgba(0, 0, 0, 255))")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralWidget.setAutoFillBackground(False)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.label_diametro = QtWidgets.QLabel(self.centralWidget)
        self.label_diametro.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_diametro.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_diametro.setObjectName("label_diametro")
        self.label_Flujo = QtWidgets.QLabel(self.centralWidget)
        self.label_Flujo.setGeometry(QtCore.QRect(10, 100, 60, 16))
        self.label_Flujo.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_Flujo.setObjectName("label_Flujo")
        self.label_Variable1 = QtWidgets.QLabel(self.centralWidget)
        self.label_Variable1.setGeometry(QtCore.QRect(10, 130, 91, 16))
        self.label_Variable1.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_Variable1.setObjectName("label_Variable1")
        self.label_Variable2 = QtWidgets.QLabel(self.centralWidget)
        self.label_Variable2.setGeometry(QtCore.QRect(10, 160, 91, 16))
        self.label_Variable2.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_Variable2.setObjectName("label_Variable2")
        self.label_title = QtWidgets.QLabel(self.centralWidget)
        self.label_title.setGeometry(QtCore.QRect(120, 20, 131, 31))
        self.label_title.setAutoFillBackground(False)
        self.label_title.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_title.setObjectName("label_title")
        self.horizontalSlider_Diametro = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSlider_Diametro.setGeometry(QtCore.QRect(100, 70, 181, 22))
        self.horizontalSlider_Diametro.setStyleSheet("background: #999999;\n"
"border-top-right-radius: 9px;\n"
"border-bottom-right-radius: 9px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;")
        self.horizontalSlider_Diametro.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Diametro.setObjectName("horizontalSlider_Diametro")
        self.label_ValDiametro = QtWidgets.QLabel(self.centralWidget)
        self.label_ValDiametro.setGeometry(QtCore.QRect(290, 70, 31, 21))
        self.label_ValDiametro.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_ValDiametro.setObjectName("label_ValDiametro")
        self.horizontalSlider_Flujo = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSlider_Flujo.setGeometry(QtCore.QRect(100, 100, 181, 22))
        self.horizontalSlider_Flujo.setStyleSheet("background: #999999;\n"
"border-top-right-radius: 9px;\n"
"border-bottom-right-radius: 9px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"")
        self.horizontalSlider_Flujo.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Flujo.setObjectName("horizontalSlider_Flujo")
        self.label_ValFlujo = QtWidgets.QLabel(self.centralWidget)
        self.label_ValFlujo.setGeometry(QtCore.QRect(290, 100, 31, 16))
        self.label_ValFlujo.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_ValFlujo.setObjectName("label_ValFlujo")
        self.horizontalSlider_Variable1 = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSlider_Variable1.setGeometry(QtCore.QRect(100, 130, 181, 22))
        self.horizontalSlider_Variable1.setStyleSheet("background: #999999;\n"
"border-top-right-radius: 9px;\n"
"border-bottom-right-radius: 9px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;")
        self.horizontalSlider_Variable1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Variable1.setObjectName("horizontalSlider_Variable1")
        self.horizontalSlider_Variable2 = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSlider_Variable2.setGeometry(QtCore.QRect(100, 160, 181, 22))
        self.horizontalSlider_Variable2.setStyleSheet("background: #999999;\n"
"border-top-right-radius: 9px;\n"
"border-bottom-right-radius: 9px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;")
        self.horizontalSlider_Variable2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Variable2.setObjectName("horizontalSlider_Variable2")
        self.label_ValVariable1 = QtWidgets.QLabel(self.centralWidget)
        self.label_ValVariable1.setGeometry(QtCore.QRect(290, 130, 31, 16))
        self.label_ValVariable1.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_ValVariable1.setObjectName("label_ValVariable1")
        self.label_ValVariable2 = QtWidgets.QLabel(self.centralWidget)
        self.label_ValVariable2.setGeometry(QtCore.QRect(290, 160, 31, 16))
        self.label_ValVariable2.setStyleSheet("color:white;\n"
"font: 25 18pt \"Helvetica\";\n"
"background:none;")
        self.label_ValVariable2.setObjectName("label_ValVariable2")
        self.pushButton_ok = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_ok.setGeometry(QtCore.QRect(130, 200, 113, 32))
        self.pushButton_ok.setStyleSheet("background:none")
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.label_UnitsDiametro = QtWidgets.QLabel(self.centralWidget)
        self.label_UnitsDiametro.setGeometry(QtCore.QRect(320, 70, 41, 16))
        self.label_UnitsDiametro.setStyleSheet("font: 25 18pt \"Helvetica\";\n"
"background:none;\n"
"color:white;")
        self.label_UnitsDiametro.setObjectName("label_UnitsDiametro")
        self.label_UnitsFlujo = QtWidgets.QLabel(self.centralWidget)
        self.label_UnitsFlujo.setGeometry(QtCore.QRect(320, 100, 41, 16))
        self.label_UnitsFlujo.setStyleSheet("font: 25 18pt \"Helvetica\";\n"
"background:none;\n"
"color:white;")
        self.label_UnitsFlujo.setObjectName("label_UnitsFlujo")
        self.label_UnitsVariable1 = QtWidgets.QLabel(self.centralWidget)
        self.label_UnitsVariable1.setGeometry(QtCore.QRect(320, 130, 41, 16))
        self.label_UnitsVariable1.setStyleSheet("font: 25 18pt \"Helvetica\";\n"
"background:none;\n"
"color:white;")
        self.label_UnitsVariable1.setObjectName("label_UnitsVariable1")
        self.label_UnitsVariable2 = QtWidgets.QLabel(self.centralWidget)
        self.label_UnitsVariable2.setGeometry(QtCore.QRect(320, 160, 41, 16))
        self.label_UnitsVariable2.setStyleSheet("font: 25 18pt \"Helvetica\";\n"
"background:none;\n"
"color:white;")
        self.label_UnitsVariable2.setObjectName("label_UnitsVariable2")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 370, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quirema"))
        self.label_diametro.setText(_translate("MainWindow", "Diametro:"))
        self.label_Flujo.setText(_translate("MainWindow", "Flujo:"))
        self.label_Variable1.setText(_translate("MainWindow", "Variable 1:"))
        self.label_Variable2.setText(_translate("MainWindow", "Variable 2:"))
        self.label_title.setText(_translate("MainWindow", "Set Up Bomba"))
        self.label_ValDiametro.setText(_translate("MainWindow", "0.0"))
        self.label_ValFlujo.setText(_translate("MainWindow", "0.0"))
        self.label_ValVariable1.setText(_translate("MainWindow", "0.0"))
        self.label_ValVariable2.setText(_translate("MainWindow", "0.0"))
        self.pushButton_ok.setText(_translate("MainWindow", "OK"))
        self.label_UnitsDiametro.setText(_translate("MainWindow", "mm"))
        self.label_UnitsFlujo.setText(_translate("MainWindow", "mm"))
        self.label_UnitsVariable1.setText(_translate("MainWindow", "mm"))
        self.label_UnitsVariable2.setText(_translate("MainWindow", "mm"))
        print("set up bomba !!!!!!! XXXX")

if __name__ == "__main__":
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet('QMainWindow{background-color: qlineargradient(spread:reflect, x1:1, y1:0, x2:0, y2:1, stop:0 rgba(0, 64, 128, 255), stop:1 rgba(0, 0, 0, 255)); border:2px solid black;}')
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    qPoint = QPoint(0,-5)
    MainWindow.move(qPoint)
    MainWindow.show()
    sys.exit(app.exec_())
