# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow4.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import Home

class Ui_MainWindow_Alarms(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(280, 100, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton.setGeometry(QtCore.QRect(320, 210, 21, 31))
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_2.setGeometry(QtCore.QRect(320, 260, 21, 31))
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_3.setGeometry(QtCore.QRect(320, 310, 21, 31))
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_4.setGeometry(QtCore.QRect(320, 360, 21, 31))
        self.radioButton_4.setText("")
        self.radioButton_4.setObjectName("radioButton_4")

        buttonStyle = "background-color: #FFFFFF; border-color: #AFAFAF; padding: 6px; font-size: 25pt;"

        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 212, 31, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet(buttonStyle)

        self.pushButton1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton1.setGeometry(QtCore.QRect(440, 262, 31, 31))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton1.setStyleSheet(buttonStyle)

        self.pushButton2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton2.setGeometry(QtCore.QRect(440, 312, 31, 31))
        self.pushButton2.setObjectName("pushButton1")
        self.pushButton2.setStyleSheet(buttonStyle)

        self.pushButton3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton3.setGeometry(QtCore.QRect(440, 362, 31, 31))
        self.pushButton3.setObjectName("pushButton1")
        self.pushButton3.setStyleSheet(buttonStyle)

        self.pushButton4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton4.setGeometry(QtCore.QRect(520, 212, 31, 31))
        self.pushButton4.setObjectName("pushButton")
        self.pushButton4.setStyleSheet(buttonStyle)

        self.pushButton5 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton5.setGeometry(QtCore.QRect(520, 262, 31, 31))
        self.pushButton5.setObjectName("pushButton")
        self.pushButton5.setStyleSheet(buttonStyle)

        self.pushButton6 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton6.setGeometry(QtCore.QRect(520, 312, 31, 31))
        self.pushButton6.setObjectName("pushButton")
        self.pushButton6.setStyleSheet(buttonStyle)

        self.pushButton7 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton7.setGeometry(QtCore.QRect(520, 362, 31, 31))
        self.pushButton7.setObjectName("pushButton")
        self.pushButton7.setStyleSheet(buttonStyle)

        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(100, 200, 191, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(100, 250, 191, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(100, 300, 191, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(100, 350, 191, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(290, 160, 81, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(480, 200, 41, 51))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(480, 250, 41, 51))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(480, 300, 41, 51))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(480, 350, 41, 51))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(480, 160, 51, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(590, 200, 81, 51))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(590, 250, 81, 51))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(590, 300, 81, 51))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralWidget)
        self.label_15.setGeometry(QtCore.QRect(590, 350, 81, 51))
        self.label_15.setObjectName("label_15")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 464, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        styleLabels = "color:white; font-size: 16pt;"
        self.label.setStyleSheet("color:white; font-size: 20pt;")
        self.label_2.setStyleSheet(styleLabels)
        self.label_3.setStyleSheet(styleLabels)
        self.label_4.setStyleSheet(styleLabels)
        self.label_5.setStyleSheet(styleLabels)
        self.label_6.setStyleSheet(styleLabels)
        self.label_7.setStyleSheet(styleLabels)
        self.label_8.setStyleSheet(styleLabels)
        self.label_9.setStyleSheet(styleLabels)
        self.label_10.setStyleSheet(styleLabels)
        self.label_11.setStyleSheet(styleLabels)
        self.label_12.setStyleSheet(styleLabels)
        self.label_13.setStyleSheet(styleLabels)
        self.label_14.setStyleSheet(styleLabels)
        self.label_15.setStyleSheet(styleLabels)

        self.label0 = QtWidgets.QLabel(self.centralWidget)
        self.label0.setGeometry(QtCore.QRect(0, 0, 800, 71))
        self.label0.setText("               Alarmas")
        self.label0.setStyleSheet("background-color: black; color:white; font-size: 22pt;")
        self.label0.setScaledContents(True)

        self.label1 = QtWidgets.QLabel(self.centralWidget)
        self.label1.setGeometry(QtCore.QRect(644, 0, 120, 71))
        self.label1.setText("")
        self.label1.setPixmap(QtGui.QPixmap("../images/quirema.png"))
        self.label1.setScaledContents(True)
        self.label1.setObjectName("label")

        self.pushButton0 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton0.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.pushButton0.setStyleSheet("background-color: black; color:white; font-size: 22pt;")
        self.pushButton0.setIcon(QtGui.QIcon('../images/home.png'))
        self.pushButton0.setIconSize(QtCore.QSize(31,31))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Alarmas", "Alarmas"))
        self.label.setText(_translate("MainWindow", "Configuración alarmas "))
        self.label_2.setText(_translate("MainWindow", "Temperatura mantas"))
        self.label_3.setText(_translate("MainWindow", "Temperatura reactor"))
        self.label_4.setText(_translate("MainWindow", "Presion"))
        self.label_5.setText(_translate("MainWindow", "Flujo masico"))
        self.label_6.setText(_translate("MainWindow", "ON/OFF"))
        self.label_7.setText(_translate("MainWindow", "0.0"))
        self.label_8.setText(_translate("MainWindow", "0.0"))
        self.label_9.setText(_translate("MainWindow", "0.0"))
        self.label_10.setText(_translate("MainWindow", "0.0"))
        self.label_11.setText(_translate("MainWindow", "Valor"))
        self.label_12.setText(_translate("MainWindow", "Celcius"))
        self.label_13.setText(_translate("MainWindow", "mL/min"))
        self.label_14.setText(_translate("MainWindow", "Celcius"))
        self.label_15.setText(_translate("MainWindow", "Bar"))

        self.pushButton.setText(_translate("MainWindow", "<"))
        self.pushButton1.setText(_translate("MainWindow", "<"))
        self.pushButton2.setText(_translate("MainWindow", "<"))
        self.pushButton3.setText(_translate("MainWindow", "<"))

        self.pushButton4.setText(_translate("MainWindow", ">"))
        self.pushButton5.setText(_translate("MainWindow", ">"))
        self.pushButton6.setText(_translate("MainWindow", ">"))
        self.pushButton7.setText(_translate("MainWindow", ">"))

        self.pushButton0.clicked.connect(self.home)
    def home(self):
        self.home = Home.Ui_MainWindow()
        self.home.setupUi(self.MainWindow)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet('QMainWindow{background-color: #BDBDBD; border:2px solid black;}')
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_Alarms()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
