/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_5;
    QFrame *line_6;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QPushButton *pushButton_9;
    QLabel *label_19;
    QPushButton *pushButton_10;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QLabel *label_20;
    QLabel *label_21;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QPushButton *pushButton_15;
    QPushButton *pushButton_16;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QFrame *line_7;
    QFrame *line_8;
    QFrame *line_9;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QPushButton *pushButton_19;
    QPushButton *pushButton_20;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QFrame *line_10;
    QFrame *line_11;
    QFrame *line_12;
    QFrame *line_13;
    QFrame *line_14;
    QFrame *line_15;
    QPushButton *pushButton_21;
    QPushButton *pushButton_22;
    QLabel *label_45;
    QFrame *line_16;
    QFrame *line_17;
    QFrame *line_18;
    QFrame *line_19;
    QFrame *line_20;
    QFrame *line_21;
    QPushButton *pushButton_33;
    QFrame *line_22;
    QFrame *line_23;
    QFrame *line_24;
    QFrame *line_25;
    QFrame *line_26;
    QFrame *line_27;
    QFrame *line_28;
    QFrame *line_29;
    QFrame *line_30;
    QFrame *line_31;
    QFrame *line_32;
    QFrame *line_33;
    QFrame *line_34;
    QFrame *line_35;
    QFrame *line_36;
    QFrame *line_37;
    QFrame *line_38;
    QFrame *line_39;
    QFrame *line_40;
    QFrame *line_41;
    QFrame *line_42;
    QFrame *line_43;
    QFrame *line_44;
    QFrame *line_45;
    QFrame *line_46;
    QFrame *line_47;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QPushButton *pushButton_34;
    QLabel *label_51;
    QLabel *label_52;
    QPushButton *pushButton_23;
    QPushButton *pushButton_24;
    QPushButton *pushButton_25;
    QPushButton *pushButton_26;
    QPushButton *pushButton_27;
    QPushButton *pushButton_28;
    QPushButton *pushButton_29;
    QPushButton *pushButton_30;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(800, 480);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(81, 82, 83, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(121, 123, 125, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(101, 102, 104, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(40, 41, 41, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(54, 54, 55, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QBrush brush6(QColor(0, 0, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        QBrush brush7(QColor(255, 255, 220, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        MainWindow->setPalette(palette);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(0, 0, 800, 31));
        QFont font;
        font.setPointSize(21);
        label->setFont(font);
        label->setStyleSheet(QLatin1String("background-color:rgb(0, 0, 0);\n"
"color:rgb(255, 255, 255)"));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(750, 0, 51, 31));
        label_2->setPixmap(QPixmap(QString::fromUtf8("../../images/quirema.png")));
        label_2->setScaledContents(true);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(630, 70, 41, 91));
        label_3->setStyleSheet(QStringLiteral("background-color : #0174DF;"));
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(630, 160, 41, 31));
        label_4->setStyleSheet(QStringLiteral(""));
        label_4->setPixmap(QPixmap(QString::fromUtf8("../../images/trapezoide.png")));
        label_4->setScaledContents(true);
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(640, 190, 21, 101));
        label_5->setStyleSheet(QStringLiteral("background-color : #0174DF;"));
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(640, 300, 21, 41));
        label_6->setStyleSheet(QStringLiteral("background-color : #0174DF;"));
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(660, 200, 51, 51));
        label_7->setStyleSheet(QStringLiteral("background-color : #1C1C1C; border-radius: 20px"));
        line = new QFrame(centralWidget);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(650, 80, 41, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralWidget);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(680, 90, 20, 111));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(centralWidget);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(680, 250, 20, 71));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralWidget);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(650, 310, 41, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(centralWidget);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(640, 340, 20, 81));
        line_5->setFrameShape(QFrame::VLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(centralWidget);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(640, 50, 20, 21));
        line_6->setFrameShape(QFrame::VLine);
        line_6->setFrameShadow(QFrame::Sunken);
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setEnabled(false);
        pushButton->setGeometry(QRect(740, 30, 61, 32));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(740, 50, 61, 32));
        pushButton_3 = new QPushButton(centralWidget);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(740, 70, 61, 32));
        pushButton_4 = new QPushButton(centralWidget);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(740, 90, 61, 32));
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(720, 40, 21, 16));
        label_8->setStyleSheet(QStringLiteral("color:white;"));
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(720, 60, 21, 16));
        label_9->setStyleSheet(QStringLiteral("color:white;"));
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(720, 80, 21, 16));
        label_10->setStyleSheet(QStringLiteral("color:white;"));
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(720, 100, 21, 16));
        label_11->setStyleSheet(QStringLiteral("color:white;"));
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(720, 160, 21, 16));
        label_13 = new QLabel(centralWidget);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(720, 200, 21, 16));
        pushButton_5 = new QPushButton(centralWidget);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(740, 190, 61, 32));
        pushButton_6 = new QPushButton(centralWidget);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(740, 150, 61, 32));
        pushButton_7 = new QPushButton(centralWidget);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(740, 130, 61, 32));
        pushButton_8 = new QPushButton(centralWidget);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(740, 170, 61, 32));
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(720, 140, 21, 16));
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(720, 180, 21, 16));
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(720, 300, 21, 16));
        label_16->setStyleSheet(QStringLiteral("color:white;"));
        label_17 = new QLabel(centralWidget);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(720, 260, 21, 16));
        label_17->setStyleSheet(QStringLiteral("color:white;"));
        label_18 = new QLabel(centralWidget);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(720, 280, 21, 16));
        label_18->setStyleSheet(QStringLiteral("color:white;"));
        pushButton_9 = new QPushButton(centralWidget);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(740, 250, 61, 32));
        label_19 = new QLabel(centralWidget);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(720, 240, 21, 16));
        label_19->setStyleSheet(QStringLiteral("color:white;"));
        pushButton_10 = new QPushButton(centralWidget);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(740, 230, 61, 32));
        pushButton_11 = new QPushButton(centralWidget);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(740, 290, 61, 32));
        pushButton_12 = new QPushButton(centralWidget);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(740, 270, 61, 32));
        label_20 = new QLabel(centralWidget);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(720, 360, 21, 16));
        label_21 = new QLabel(centralWidget);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(720, 380, 21, 16));
        pushButton_13 = new QPushButton(centralWidget);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(740, 350, 61, 32));
        pushButton_14 = new QPushButton(centralWidget);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(740, 370, 61, 32));
        pushButton_15 = new QPushButton(centralWidget);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(740, 330, 61, 32));
        pushButton_16 = new QPushButton(centralWidget);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(740, 390, 61, 32));
        label_22 = new QLabel(centralWidget);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(720, 400, 21, 16));
        label_23 = new QLabel(centralWidget);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(720, 340, 21, 16));
        label_24 = new QLabel(centralWidget);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(580, 110, 21, 91));
        label_24->setStyleSheet(QStringLiteral("background-color : #0174DF;"));
        label_25 = new QLabel(centralWidget);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(380, 190, 211, 161));
        label_25->setStyleSheet(QStringLiteral(""));
        label_25->setPixmap(QPixmap(QString::fromUtf8("../../images/valve.png")));
        label_25->setScaledContents(true);
        label_26 = new QLabel(centralWidget);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(640, 290, 21, 20));
        label_26->setStyleSheet(QStringLiteral("background-color : black"));
        label_27 = new QLabel(centralWidget);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(500, 370, 101, 31));
        label_27->setStyleSheet(QStringLiteral("color:black; background-color:#0174DF;qproperty-alignment: AlignCenter;"));
        line_7 = new QFrame(centralWidget);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(530, 340, 20, 31));
        line_7->setFrameShape(QFrame::VLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(centralWidget);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(570, 230, 21, 20));
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(centralWidget);
        line_9->setObjectName(QStringLiteral("line_9"));
        line_9->setGeometry(QRect(580, 200, 20, 41));
        line_9->setFrameShape(QFrame::VLine);
        line_9->setFrameShadow(QFrame::Sunken);
        label_28 = new QLabel(centralWidget);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(190, 330, 81, 71));
        label_28->setStyleSheet(QStringLiteral("background-color:#0174DF; border-radius: 20px;qproperty-alignment: AlignCenter;"));
        label_29 = new QLabel(centralWidget);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(80, 360, 81, 21));
        label_29->setStyleSheet(QStringLiteral("background-color:#0174DF;qproperty-alignment: AlignCenter;"));
        label_30 = new QLabel(centralWidget);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(20, 360, 51, 21));
        label_30->setStyleSheet(QStringLiteral("background-color:#0174DF;qproperty-alignment: AlignCenter;"));
        pushButton_17 = new QPushButton(centralWidget);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(90, 310, 101, 32));
        pushButton_18 = new QPushButton(centralWidget);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(90, 330, 101, 32));
        pushButton_19 = new QPushButton(centralWidget);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(10, 380, 131, 32));
        pushButton_20 = new QPushButton(centralWidget);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(10, 400, 121, 32));
        label_31 = new QLabel(centralWidget);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(250, 260, 81, 61));
        label_31->setStyleSheet(QStringLiteral("background-color:#0174DF;border-radius: 20px;qproperty-alignment: AlignCenter;"));
        label_32 = new QLabel(centralWidget);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(90, 250, 41, 31));
        label_32->setStyleSheet(QStringLiteral("background-color:#0174DF;qproperty-alignment: AlignCenter;"));
        label_33 = new QLabel(centralWidget);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(160, 60, 41, 21));
        label_33->setStyleSheet(QStringLiteral("background-color:#0174DF;qproperty-alignment: AlignCenter;"));
        label_34 = new QLabel(centralWidget);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(190, 90, 41, 21));
        label_34->setStyleSheet(QStringLiteral("background-color:#0174DF;qproperty-alignment: AlignCenter;"));
        label_35 = new QLabel(centralWidget);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(190, 130, 41, 21));
        label_35->setStyleSheet(QStringLiteral("background-color:#0174DF;qproperty-alignment: AlignCenter;"));
        label_36 = new QLabel(centralWidget);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(160, 160, 41, 21));
        label_36->setStyleSheet(QStringLiteral("background-color:#0174DF;qproperty-alignment: AlignCenter;"));
        label_37 = new QLabel(centralWidget);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(180, 190, 41, 21));
        label_37->setStyleSheet(QStringLiteral("background-color:#0174DF;qproperty-alignment: AlignCenter;"));
        label_38 = new QLabel(centralWidget);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(160, 220, 41, 21));
        label_38->setStyleSheet(QStringLiteral("background-color:#0174DF;qproperty-alignment: AlignCenter;"));
        label_39 = new QLabel(centralWidget);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(140, 60, 21, 20));
        label_39->setStyleSheet(QStringLiteral("color:white;"));
        label_40 = new QLabel(centralWidget);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(140, 90, 51, 20));
        label_40->setStyleSheet(QStringLiteral("color:white;"));
        label_41 = new QLabel(centralWidget);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(140, 130, 51, 20));
        label_41->setStyleSheet(QStringLiteral("color:white;"));
        label_42 = new QLabel(centralWidget);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(140, 160, 21, 20));
        label_42->setStyleSheet(QStringLiteral("color:white;"));
        label_43 = new QLabel(centralWidget);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(140, 190, 41, 20));
        label_43->setStyleSheet(QStringLiteral("color:white;"));
        label_44 = new QLabel(centralWidget);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(140, 220, 21, 20));
        label_44->setStyleSheet(QStringLiteral("color:white;"));
        line_10 = new QFrame(centralWidget);
        line_10->setObjectName(QStringLiteral("line_10"));
        line_10->setGeometry(QRect(200, 50, 191, 20));
        line_10->setFrameShape(QFrame::HLine);
        line_10->setFrameShadow(QFrame::Sunken);
        line_11 = new QFrame(centralWidget);
        line_11->setObjectName(QStringLiteral("line_11"));
        line_11->setGeometry(QRect(230, 80, 141, 20));
        line_11->setFrameShape(QFrame::HLine);
        line_11->setFrameShadow(QFrame::Sunken);
        line_12 = new QFrame(centralWidget);
        line_12->setObjectName(QStringLiteral("line_12"));
        line_12->setGeometry(QRect(230, 120, 161, 20));
        line_12->setFrameShape(QFrame::HLine);
        line_12->setFrameShadow(QFrame::Sunken);
        line_13 = new QFrame(centralWidget);
        line_13->setObjectName(QStringLiteral("line_13"));
        line_13->setGeometry(QRect(200, 150, 191, 20));
        line_13->setFrameShape(QFrame::HLine);
        line_13->setFrameShadow(QFrame::Sunken);
        line_14 = new QFrame(centralWidget);
        line_14->setObjectName(QStringLiteral("line_14"));
        line_14->setGeometry(QRect(220, 180, 171, 20));
        line_14->setFrameShape(QFrame::HLine);
        line_14->setFrameShadow(QFrame::Sunken);
        line_15 = new QFrame(centralWidget);
        line_15->setObjectName(QStringLiteral("line_15"));
        line_15->setGeometry(QRect(200, 220, 71, 20));
        line_15->setFrameShape(QFrame::HLine);
        line_15->setFrameShadow(QFrame::Sunken);
        pushButton_21 = new QPushButton(centralWidget);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(10, 60, 61, 16));
        pushButton_22 = new QPushButton(centralWidget);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(80, 60, 51, 16));
        label_45 = new QLabel(centralWidget);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(370, 80, 41, 31));
        label_45->setStyleSheet(QStringLiteral("background-color:#0174DF"));
        line_16 = new QFrame(centralWidget);
        line_16->setObjectName(QStringLiteral("line_16"));
        line_16->setGeometry(QRect(380, 61, 20, 20));
        line_16->setFrameShape(QFrame::VLine);
        line_16->setFrameShadow(QFrame::Sunken);
        line_17 = new QFrame(centralWidget);
        line_17->setObjectName(QStringLiteral("line_17"));
        line_17->setGeometry(QRect(380, 110, 20, 81));
        line_17->setFrameShape(QFrame::VLine);
        line_17->setFrameShadow(QFrame::Sunken);
        line_18 = new QFrame(centralWidget);
        line_18->setObjectName(QStringLiteral("line_18"));
        line_18->setGeometry(QRect(410, 180, 3, 61));
        line_18->setFrameShape(QFrame::VLine);
        line_18->setFrameShadow(QFrame::Sunken);
        line_19 = new QFrame(centralWidget);
        line_19->setObjectName(QStringLiteral("line_19"));
        line_19->setGeometry(QRect(410, 170, 31, 16));
        line_19->setFrameShape(QFrame::HLine);
        line_19->setFrameShadow(QFrame::Sunken);
        line_20 = new QFrame(centralWidget);
        line_20->setObjectName(QStringLiteral("line_20"));
        line_20->setGeometry(QRect(430, 100, 20, 81));
        line_20->setFrameShape(QFrame::VLine);
        line_20->setFrameShadow(QFrame::Sunken);
        line_21 = new QFrame(centralWidget);
        line_21->setObjectName(QStringLiteral("line_21"));
        line_21->setGeometry(QRect(410, 90, 31, 16));
        line_21->setFrameShape(QFrame::HLine);
        line_21->setFrameShadow(QFrame::Sunken);
        pushButton_33 = new QPushButton(centralWidget);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(0, 0, 71, 32));
        line_22 = new QFrame(centralWidget);
        line_22->setObjectName(QStringLiteral("line_22"));
        line_22->setGeometry(QRect(230, 410, 421, 20));
        line_22->setFrameShape(QFrame::HLine);
        line_22->setFrameShadow(QFrame::Sunken);
        line_23 = new QFrame(centralWidget);
        line_23->setObjectName(QStringLiteral("line_23"));
        line_23->setGeometry(QRect(220, 400, 20, 20));
        line_23->setFrameShape(QFrame::VLine);
        line_23->setFrameShadow(QFrame::Sunken);
        line_24 = new QFrame(centralWidget);
        line_24->setObjectName(QStringLiteral("line_24"));
        line_24->setGeometry(QRect(620, 40, 31, 20));
        line_24->setFrameShape(QFrame::HLine);
        line_24->setFrameShadow(QFrame::Sunken);
        line_25 = new QFrame(centralWidget);
        line_25->setObjectName(QStringLiteral("line_25"));
        line_25->setGeometry(QRect(610, 50, 20, 251));
        line_25->setFrameShape(QFrame::VLine);
        line_25->setFrameShadow(QFrame::Sunken);
        line_26 = new QFrame(centralWidget);
        line_26->setObjectName(QStringLiteral("line_26"));
        line_26->setGeometry(QRect(570, 290, 51, 20));
        line_26->setFrameShape(QFrame::HLine);
        line_26->setFrameShadow(QFrame::Sunken);
        line_27 = new QFrame(centralWidget);
        line_27->setObjectName(QStringLiteral("line_27"));
        line_27->setGeometry(QRect(580, 70, 20, 41));
        line_27->setFrameShape(QFrame::VLine);
        line_27->setFrameShadow(QFrame::Sunken);
        line_28 = new QFrame(centralWidget);
        line_28->setObjectName(QStringLiteral("line_28"));
        line_28->setGeometry(QRect(540, 60, 51, 20));
        line_28->setFrameShape(QFrame::HLine);
        line_28->setFrameShadow(QFrame::Sunken);
        line_29 = new QFrame(centralWidget);
        line_29->setObjectName(QStringLiteral("line_29"));
        line_29->setGeometry(QRect(530, 70, 20, 131));
        line_29->setFrameShape(QFrame::VLine);
        line_29->setFrameShadow(QFrame::Sunken);
        line_30 = new QFrame(centralWidget);
        line_30->setObjectName(QStringLiteral("line_30"));
        line_30->setGeometry(QRect(290, 320, 20, 51));
        line_30->setFrameShape(QFrame::VLine);
        line_30->setFrameShadow(QFrame::Sunken);
        line_31 = new QFrame(centralWidget);
        line_31->setObjectName(QStringLiteral("line_31"));
        line_31->setGeometry(QRect(300, 360, 191, 20));
        line_31->setFrameShape(QFrame::HLine);
        line_31->setFrameShadow(QFrame::Sunken);
        line_32 = new QFrame(centralWidget);
        line_32->setObjectName(QStringLiteral("line_32"));
        line_32->setGeometry(QRect(480, 350, 20, 21));
        line_32->setFrameShape(QFrame::VLine);
        line_32->setFrameShadow(QFrame::Sunken);
        line_33 = new QFrame(centralWidget);
        line_33->setObjectName(QStringLiteral("line_33"));
        line_33->setGeometry(QRect(110, 290, 141, 20));
        line_33->setFrameShape(QFrame::HLine);
        line_33->setFrameShadow(QFrame::Sunken);
        line_34 = new QFrame(centralWidget);
        line_34->setObjectName(QStringLiteral("line_34"));
        line_34->setGeometry(QRect(100, 280, 20, 21));
        line_34->setFrameShape(QFrame::VLine);
        line_34->setFrameShadow(QFrame::Sunken);
        line_35 = new QFrame(centralWidget);
        line_35->setObjectName(QStringLiteral("line_35"));
        line_35->setGeometry(QRect(230, 240, 121, 20));
        line_35->setFrameShape(QFrame::HLine);
        line_35->setFrameShadow(QFrame::Sunken);
        line_36 = new QFrame(centralWidget);
        line_36->setObjectName(QStringLiteral("line_36"));
        line_36->setGeometry(QRect(340, 250, 20, 41));
        line_36->setFrameShape(QFrame::VLine);
        line_36->setFrameShadow(QFrame::Sunken);
        line_37 = new QFrame(centralWidget);
        line_37->setObjectName(QStringLiteral("line_37"));
        line_37->setGeometry(QRect(220, 250, 20, 41));
        line_37->setFrameShape(QFrame::VLine);
        line_37->setFrameShadow(QFrame::Sunken);
        line_38 = new QFrame(centralWidget);
        line_38->setObjectName(QStringLiteral("line_38"));
        line_38->setGeometry(QRect(230, 280, 21, 16));
        line_38->setFrameShape(QFrame::HLine);
        line_38->setFrameShadow(QFrame::Sunken);
        line_39 = new QFrame(centralWidget);
        line_39->setObjectName(QStringLiteral("line_39"));
        line_39->setGeometry(QRect(330, 280, 21, 16));
        line_39->setFrameShape(QFrame::HLine);
        line_39->setFrameShadow(QFrame::Sunken);
        line_40 = new QFrame(centralWidget);
        line_40->setObjectName(QStringLiteral("line_40"));
        line_40->setGeometry(QRect(260, 230, 20, 31));
        line_40->setFrameShape(QFrame::VLine);
        line_40->setFrameShadow(QFrame::Sunken);
        line_41 = new QFrame(centralWidget);
        line_41->setObjectName(QStringLiteral("line_41"));
        line_41->setGeometry(QRect(380, 290, 31, 20));
        line_41->setFrameShape(QFrame::HLine);
        line_41->setFrameShadow(QFrame::Sunken);
        line_42 = new QFrame(centralWidget);
        line_42->setObjectName(QStringLiteral("line_42"));
        line_42->setGeometry(QRect(370, 230, 20, 71));
        line_42->setFrameShape(QFrame::VLine);
        line_42->setFrameShadow(QFrame::Sunken);
        line_43 = new QFrame(centralWidget);
        line_43->setObjectName(QStringLiteral("line_43"));
        line_43->setGeometry(QRect(300, 220, 81, 20));
        line_43->setFrameShape(QFrame::HLine);
        line_43->setFrameShadow(QFrame::Sunken);
        line_44 = new QFrame(centralWidget);
        line_44->setObjectName(QStringLiteral("line_44"));
        line_44->setGeometry(QRect(290, 230, 20, 31));
        line_44->setFrameShape(QFrame::VLine);
        line_44->setFrameShadow(QFrame::Sunken);
        line_45 = new QFrame(centralWidget);
        line_45->setObjectName(QStringLiteral("line_45"));
        line_45->setGeometry(QRect(370, 200, 71, 20));
        line_45->setFrameShape(QFrame::HLine);
        line_45->setFrameShadow(QFrame::Sunken);
        line_46 = new QFrame(centralWidget);
        line_46->setObjectName(QStringLiteral("line_46"));
        line_46->setGeometry(QRect(360, 210, 20, 181));
        line_46->setFrameShape(QFrame::VLine);
        line_46->setFrameShadow(QFrame::Sunken);
        line_47 = new QFrame(centralWidget);
        line_47->setObjectName(QStringLiteral("line_47"));
        line_47->setGeometry(QRect(270, 380, 101, 20));
        line_47->setFrameShape(QFrame::HLine);
        line_47->setFrameShadow(QFrame::Sunken);
        label_46 = new QLabel(centralWidget);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(360, 360, 21, 21));
        label_46->setPixmap(QPixmap(QString::fromUtf8("../../images/cruceLineaHorizontal.png")));
        label_46->setScaledContents(true);
        label_47 = new QLabel(centralWidget);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(400, 200, 21, 21));
        label_47->setPixmap(QPixmap(QString::fromUtf8("../../images/cruceLineaVertical.png")));
        label_47->setScaledContents(true);
        label_48 = new QLabel(centralWidget);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(360, 220, 21, 21));
        label_48->setPixmap(QPixmap(QString::fromUtf8("../../images/cruceLineaVertical.png")));
        label_48->setScaledContents(true);
        label_49 = new QLabel(centralWidget);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(290, 240, 21, 21));
        label_49->setPixmap(QPixmap(QString::fromUtf8("../../images/cruceLineaVertical.png")));
        label_49->setScaledContents(true);
        label_50 = new QLabel(centralWidget);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(260, 240, 21, 21));
        label_50->setPixmap(QPixmap(QString::fromUtf8("../../images/cruceLineaVertical.png")));
        label_50->setScaledContents(true);
        pushButton_34 = new QPushButton(centralWidget);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(660, 30, 41, 32));
        label_51 = new QLabel(centralWidget);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(10, 40, 21, 16));
        label_51->setStyleSheet(QStringLiteral("color:white;"));
        label_52 = new QLabel(centralWidget);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(80, 40, 21, 16));
        label_52->setStyleSheet(QStringLiteral("color:white;"));
        pushButton_23 = new QPushButton(centralWidget);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(80, 90, 51, 16));
        pushButton_24 = new QPushButton(centralWidget);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(10, 90, 61, 16));
        pushButton_25 = new QPushButton(centralWidget);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(80, 130, 51, 16));
        pushButton_26 = new QPushButton(centralWidget);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(10, 130, 61, 16));
        pushButton_27 = new QPushButton(centralWidget);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(80, 160, 51, 16));
        pushButton_28 = new QPushButton(centralWidget);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(10, 160, 61, 16));
        pushButton_29 = new QPushButton(centralWidget);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(80, 190, 51, 16));
        pushButton_30 = new QPushButton(centralWidget);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(10, 190, 61, 16));
        pushButton_31 = new QPushButton(centralWidget);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(80, 220, 51, 16));
        pushButton_32 = new QPushButton(centralWidget);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(10, 220, 61, 16));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 800, 22));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Quirema", 0));
        label->setText(QApplication::translate("MainWindow", "                   Quirema                                     Reactor", 0));
        label_2->setText(QString());
        label_3->setText(QString());
        label_4->setText(QString());
        label_5->setText(QString());
        label_6->setText(QString());
        label_7->setText(QString());
        pushButton->setText(QApplication::translate("MainWindow", "000.0", 0));
        pushButton_2->setText(QApplication::translate("MainWindow", "000.0", 0));
        pushButton_3->setText(QApplication::translate("MainWindow", "000.0", 0));
        pushButton_4->setText(QApplication::translate("MainWindow", "000.0", 0));
        label_8->setText(QApplication::translate("MainWindow", "SV:", 0));
        label_9->setText(QApplication::translate("MainWindow", "PV:", 0));
        label_10->setText(QApplication::translate("MainWindow", "R:", 0));
        label_11->setText(QApplication::translate("MainWindow", "X:", 0));
        label_12->setText(QApplication::translate("MainWindow", "PV:", 0));
        label_13->setText(QApplication::translate("MainWindow", "X:", 0));
        pushButton_5->setText(QApplication::translate("MainWindow", "000.0", 0));
        pushButton_6->setText(QApplication::translate("MainWindow", "000.0", 0));
        pushButton_7->setText(QApplication::translate("MainWindow", "000.0", 0));
        pushButton_8->setText(QApplication::translate("MainWindow", "000.0", 0));
        label_14->setText(QApplication::translate("MainWindow", "SV:", 0));
        label_15->setText(QApplication::translate("MainWindow", "R:", 0));
        label_16->setText(QApplication::translate("MainWindow", "X:", 0));
        label_17->setText(QApplication::translate("MainWindow", "PV:", 0));
        label_18->setText(QApplication::translate("MainWindow", "R:", 0));
        pushButton_9->setText(QApplication::translate("MainWindow", "000.0", 0));
        label_19->setText(QApplication::translate("MainWindow", "SV:", 0));
        pushButton_10->setText(QApplication::translate("MainWindow", "000.0", 0));
        pushButton_11->setText(QApplication::translate("MainWindow", "000.0", 0));
        pushButton_12->setText(QApplication::translate("MainWindow", "000.0", 0));
        label_20->setText(QApplication::translate("MainWindow", "PV:", 0));
        label_21->setText(QApplication::translate("MainWindow", "R:", 0));
        pushButton_13->setText(QApplication::translate("MainWindow", "000.0", 0));
        pushButton_14->setText(QApplication::translate("MainWindow", "000.0", 0));
        pushButton_15->setText(QApplication::translate("MainWindow", "000.0", 0));
        pushButton_16->setText(QApplication::translate("MainWindow", "000.0", 0));
        label_22->setText(QApplication::translate("MainWindow", "X:", 0));
        label_23->setText(QApplication::translate("MainWindow", "SV:", 0));
        label_24->setText(QString());
        label_25->setText(QString());
        label_26->setText(QString());
        label_27->setText(QApplication::translate("MainWindow", " Analizador vent", 0));
        label_28->setText(QApplication::translate("MainWindow", "4-way valve", 0));
        label_29->setText(QApplication::translate("MainWindow", "Vaporizador", 0));
        label_30->setText(QApplication::translate("MainWindow", "Bomba", 0));
        pushButton_17->setText(QApplication::translate("MainWindow", "Temp: 100 C", 0));
        pushButton_18->setText(QApplication::translate("MainWindow", "SV: 100 C", 0));
        pushButton_19->setText(QApplication::translate("MainWindow", "Flow: 100 ml/min", 0));
        pushButton_20->setText(QApplication::translate("MainWindow", "SV: 100 ml/min", 0));
        label_31->setText(QApplication::translate("MainWindow", "6-way valve", 0));
        label_32->setText(QApplication::translate("MainWindow", "Vent", 0));
        label_33->setText(QApplication::translate("MainWindow", "MFC 1", 0));
        label_34->setText(QApplication::translate("MainWindow", "MFC 2", 0));
        label_35->setText(QApplication::translate("MainWindow", "MFC 3", 0));
        label_36->setText(QApplication::translate("MainWindow", "MFC 4", 0));
        label_37->setText(QApplication::translate("MainWindow", "MFC 5", 0));
        label_38->setText(QApplication::translate("MainWindow", "MFC 6", 0));
        label_39->setText(QApplication::translate("MainWindow", "Ar", 0));
        label_40->setText(QApplication::translate("MainWindow", "CO2/O2", 0));
        label_41->setText(QApplication::translate("MainWindow", "H2/CH4", 0));
        label_42->setText(QApplication::translate("MainWindow", "CO", 0));
        label_43->setText(QApplication::translate("MainWindow", "Etileno", 0));
        label_44->setText(QApplication::translate("MainWindow", "Ar", 0));
        pushButton_21->setText(QApplication::translate("MainWindow", "0000.0", 0));
        pushButton_22->setText(QApplication::translate("MainWindow", "0000.0", 0));
        label_45->setText(QString());
        pushButton_33->setText(QApplication::translate("MainWindow", "Home", 0));
        label_46->setText(QString());
        label_47->setText(QString());
        label_48->setText(QString());
        label_49->setText(QString());
        label_50->setText(QString());
        pushButton_34->setText(QApplication::translate("MainWindow", "Play", 0));
        label_51->setText(QApplication::translate("MainWindow", "SV:", 0));
        label_52->setText(QApplication::translate("MainWindow", "PV:", 0));
        pushButton_23->setText(QApplication::translate("MainWindow", "0000.0", 0));
        pushButton_24->setText(QApplication::translate("MainWindow", "0000.0", 0));
        pushButton_25->setText(QApplication::translate("MainWindow", "0000.0", 0));
        pushButton_26->setText(QApplication::translate("MainWindow", "0000.0", 0));
        pushButton_27->setText(QApplication::translate("MainWindow", "0000.0", 0));
        pushButton_28->setText(QApplication::translate("MainWindow", "0000.0", 0));
        pushButton_29->setText(QApplication::translate("MainWindow", "0000.0", 0));
        pushButton_30->setText(QApplication::translate("MainWindow", "0000.0", 0));
        pushButton_31->setText(QApplication::translate("MainWindow", "0000.0", 0));
        pushButton_32->setText(QApplication::translate("MainWindow", "0000.0", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
